# Auto-generated by Claude Code Generation Mode
# Record ID: 44
# Generated at: 2026-07-05 15:24:04

from manim import *
import numpy as np
import math
import sys
import os

# 添加项目根目录到路径
sys.path.insert(0, r"C:\Users\lxy\WorkBuddy\2026-06-30-16-26-23\education_agent")

# 设置音频目录环境变量（使用绝对路径）
os.environ["MATHANIM_AUDIO_DIR"] = r"C:\Users\lxy\WorkBuddy\2026-06-30-16-26-23\education_agent\output\audio\run_20260705_152354"
os.environ["MATHANIM_VIDEO_OUTPUT"] = r"C:\Users\lxy\WorkBuddy\2026-06-30-16-26-23\education_agent\output\videos"

# 导入基类
from animation.base_scene import MathAnimScene

# 设置渲染参数
config.pixel_width = 1920
config.pixel_height = 1080
config.frame_rate = 60

from manim import *
import numpy as np


class MathProblemScene(MathAnimScene):

    SCENES = [
        (1, "开场", "audio_001_开场.mp3", None),
        (2, "画圆", "audio_002_画圆.mp3", None),
        (3, "写出公式", "audio_003_写出公式.mp3", None),
        (4, "代入数值", "audio_004_代入数值.mp3", None),
        (5, "计算结果", "audio_005_计算结果.mp3", None),
        (6, "总结", "audio_006_总结.mp3", None),
    ]

    def calculate_geometry(self):
        geometry = {}
        geometry['math'] = {
            'radius': 7,
            'area_formula': 'S = pi * r^2',
            'area_exact': '49*pi',
            'area_approx': 153.86
        }

        display_radius = 2.0
        center = np.array([0.0, 0.0, 0.0])

        points = {
            'O': center,
            'P_right': center + np.array([display_radius, 0.0, 0.0]),
            'P_top': center + np.array([0.0, display_radius, 0.0]),
            'P_left': center + np.array([-display_radius, 0.0, 0.0]),
            'P_bottom': center + np.array([0.0, -display_radius, 0.0]),
        }

        lines = {
            'radius_h': Line(points['O'], points['P_right']),
            'radius_v': Line(points['O'], points['P_top']),
        }

        geometry['points'] = points
        geometry['lines'] = lines
        geometry['display_radius'] = display_radius
        geometry['center'] = center

        return geometry

    def assert_geometry(self, geometry):
        assert geometry['math']['radius'] == 7, "Radius must be 7"
        r = geometry['math']['radius']
        expected_area_exact_coef = r ** 2
        assert expected_area_exact_coef == 49, "r squared must be 49"
        self._check_canvas_bounds(geometry)

    def define_elements(self, geometry):
        elements = {}

        elements['circle'] = Circle(
            radius=geometry['display_radius'],
            color=self.COLORS['primary'],
            stroke_width=4
        )
        elements['circle'].move_to(geometry['center'])

        elements['center_dot'] = Dot(
            geometry['center'],
            color=self.COLORS['highlight'],
            radius=0.08
        )

        elements['radius_line'] = Line(
            geometry['points']['O'],
            geometry['points']['P_right'],
            color=self.COLORS['secondary'],
            stroke_width=3
        )

        elements['O_label'] = Text("O", font_size=32, color=self.COLORS['highlight'])
        elements['O_label'].next_to(geometry['center'], DOWN + LEFT, buff=0.15)

        elements['r_label'] = Text("r", font_size=36, color=self.COLORS['secondary'])
        elements['r_label'].next_to(geometry['radius_line'], UP, buff=0.1)

        elements['r_value_label'] = MathTex(r"r = 7", font_size=36, color=self.COLORS['secondary'])
        elements['r_value_label'].move_to(np.array([3.0, 1.5, 0.0]))

        return elements

    def play_scene_1(self, elements, geometry):
        expected = self.start_scene_with_audio(1)

        title = Text("求圆的面积", font_size=56, color=self.COLORS['highlight'])
        title.move_to(np.array([0.0, 1.5, 0.0]))

        subtitle = Text("半径 r = 7", font_size=42, color=self.COLORS['text'])
        subtitle.move_to(np.array([0.0, 0.0, 0.0]))

        self.subtitle = self.create_subtitle("")

        self.fade_in(title, run_time=1.0)
        self.wait_for_narration("今天")
        self.show_subtitle_timed("大家好，今天我们来学习圆的面积的计算方法。", 3.0)

        self.wait_for_narration("半径")
        self.fade_in(subtitle, run_time=0.8)

        self.wait_for_narration("求出")

        self.fade_out(title, run_time=0.5)
        self.fade_out(subtitle, run_time=0.5)

        self.end_scene_with_audio(expected)

    def play_scene_2(self, elements, geometry):
        expected = self.start_scene_with_audio(2)

        self.show_subtitle_timed("首先，我们在屏幕上画一个圆。", 2.5)

        self.wait_for_narration("圆心")
        self.fade_in(elements['center_dot'], run_time=0.5)
        self.fade_in(elements['O_label'], run_time=0.5)

        self.wait_for_narration("画一个圆")
        self.play(Create(elements['circle']), run_time=1.5)

        self.wait_for_narration("半径")
        self.play(Create(elements['radius_line']), run_time=1.0)
        self.fade_in(elements['r_label'], run_time=0.5)

        self.wait_for_narration("等于7")
        self.fade_in(elements['r_value_label'], run_time=0.8)
        self.highlight_element(elements['r_value_label'], color=self.COLORS['highlight'], scale=1.2, duration=1.0)

        self.end_scene_with_audio(expected)

    def play_scene_3(self, elements, geometry):
        expected = self.start_scene_with_audio(3)

        self.show_subtitle_timed("写出圆的面积公式。", 2.5)

        formula = MathTex(r"S = \pi r^{2}", font_size=60, color=self.COLORS['highlight'])
        formula.move_to(np.array([0.0, 2.8, 0.0]))

        self.wait_for_narration("公式")
        self.play(Write(formula), run_time=1.5)

        self.wait_for_narration("π")
        self.highlight_element(formula, color=self.COLORS['secondary'], scale=1.15, duration=1.0)

        formula_box = SurroundingRectangle(formula, color=self.COLORS['highlight'], buff=0.2)
        self.wait_for_narration("基本公式")
        self.play(Create(formula_box), run_time=0.8)

        self.elements_formula = formula
        self.elements_formula_box = formula_box

        self.end_scene_with_audio(expected)

    def play_scene_4(self, elements, geometry):
        expected = self.start_scene_with_audio(4)

        self.show_subtitle_timed("把半径代入公式。", 2.5)

        r_arrow = Arrow(
            start=np.array([3.0, 1.5, 0.0]),
            end=np.array([2.0, 2.5, 0.0]),
            color=self.COLORS['secondary'],
            stroke_width=3,
            buff=0.1
        )

        self.wait_for_narration("代入")
        self.play(Create(r_arrow), run_time=1.0)

        self.wait_for_narration("等于7")
        self.fade_out(elements['r_value_label'], run_time=0.3)

        substitution = MathTex(r"S = \pi \times 7^{2}", font_size=56, color=self.COLORS['highlight'])
        substitution.move_to(np.array([0.0, 0.8, 0.0]))

        self.play(Write(substitution), run_time=1.5)

        self.wait_for_narration("49π")
        result_form = MathTex(r"S = 49\pi", font_size=64, color=self.COLORS['primary'])
        result_form.move_to(np.array([0.0, -1.0, 0.0]))

        self.play(Write(result_form), run_time=1.5)
        self.highlight_element(result_form, color=self.COLORS['highlight'], scale=1.2, duration=1.2)

        self.elements_substitution = substitution
        self.elements_result_form = result_form
        self.elements_r_arrow = r_arrow

        self.end_scene_with_audio(expected)

    def play_scene_5(self, elements, geometry):
        expected = self.start_scene_with_audio(5)

        self.show_subtitle_timed("计算最终结果。", 2.5)

        calc_label = Text("计算过程：", font_size=32, color=self.COLORS['text'])
        calc_label.move_to(np.array([-3.5, 2.0, 0.0]))

        self.wait_for_narration("计算")
        self.fade_in(calc_label, run_time=0.6)

        calc_step1 = MathTex(r"7 \times 7 = 49", font_size=40, color=self.COLORS['text'])
        calc_step1.move_to(np.array([-3.5, 1.0, 0.0]))

        self.wait_for_narration("7的平方")
        self.play(Write(calc_step1), run_time=1.2)

        calc_step2 = MathTex(r"S = 49\pi", font_size=40, color=self.COLORS['primary'])
        calc_step2.move_to(np.array([-3.5, 0.0, 0.0]))

        self.wait_for_narration("等于49")
        self.play(Write(calc_step2), run_time=1.0)

        calc_step3 = MathTex(r"S \approx 153.86", font_size=40, color=self.COLORS['highlight'])
        calc_step3.move_to(np.array([-3.5, -1.0, 0.0]))

        self.wait_for_narration("153")
        self.play(Write(calc_step3), run_time=1.2)
        self.highlight_element(calc_step3, color=self.COLORS['highlight'], scale=1.2, duration=1.0)

        self.elements_calc_label = calc_label
        self.elements_calc_step1 = calc_step1
        self.elements_calc_step2 = calc_step2
        self.elements_calc_step3 = calc_step3

        self.end_scene_with_audio(expected)

    def play_scene_6(self, elements, geometry):
        expected = self.start_scene_with_audio(6)

        self.show_subtitle_timed("总结回顾。", 2.0)

        summary_title = Text("总结", font_size=48, color=self.COLORS['highlight'])
        summary_title.move_to(np.array([0.0, 3.2, 0.0]))

        self.wait_for_narration("总结")
        self.fade_in(summary_title, run_time=0.6)

        final_formula = MathTex(r"S = \pi r^{2}", font_size=52, color=self.COLORS['text'])
        final_formula.move_to(np.array([0.0, 2.0, 0.0]))

        final_arrow = MathTex(r"\Rightarrow", font_size=48, color=self.COLORS['secondary'])
        final_arrow.move_to(np.array([1.8, 1.0, 0.0]))

        final_answer = MathTex(r"S = 49\pi", font_size=60, color=self.COLORS['highlight'])
        final_answer.move_to(np.array([0.0, 0.2, 0.0]))

        self.wait_for_narration("公式")
        self.play(Write(final_formula), run_time=1.2)

        self.wait_for_narration("半径等于7")
        self.play(Write(final_answer), run_time=1.2)
        self.highlight_element(final_answer, color=self.COLORS['highlight'], scale=1.25, duration=1.5)

        circle_box = SurroundingRectangle(elements['circle'], color=self.COLORS['highlight'], buff=0.2)
        self.play(Create(circle_box), run_time=0.8)

        all_group = VGroup(
            elements['circle'],
            elements['center_dot'],
            elements['O_label'],
            elements['radius_line'],
            elements['r_label']
        )

        self.wait_for_narration("49π")
        self.highlight_element(all_group, color=self.COLORS['highlight'], scale=1.05, duration=1.5)

        self.end_scene_with_audio(expected)
