# Auto-generated by Claude Code Generation Mode
# Record ID: 50
# Generated at: 2026-07-05 17:28:12

from manim import *
import numpy as np
import math
import sys
import os

# 添加项目根目录到路径
sys.path.insert(0, r"C:\Users\lxy\WorkBuddy\2026-06-30-16-26-23\education_agent")

# 设置音频目录环境变量（使用绝对路径）
os.environ["MATHANIM_AUDIO_DIR"] = r"C:\Users\lxy\WorkBuddy\2026-06-30-16-26-23\education_agent\output\audio\run_20260705_172804"
os.environ["MATHANIM_VIDEO_OUTPUT"] = r"C:\Users\lxy\WorkBuddy\2026-06-30-16-26-23\education_agent\output\videos"

# 导入基类
from animation.base_scene import MathAnimScene

# 设置渲染参数
config.pixel_width = 1920
config.pixel_height = 1080
config.frame_rate = 60

from manim import *
import numpy as np


class MathProblemScene(MathAnimScene):
    SCENES = [
        (1, '开场', 'audio_001_开场.mp3', None),
        (2, '画三角形', 'audio_002_画三角形.mp3', None),
        (3, '标注边长', 'audio_003_标注边长.mp3', None),
        (4, '写出公式', 'audio_004_写出公式.mp3', None),
        (5, '计算结果', 'audio_005_计算结果.mp3', None),
        (6, '总结', 'audio_006_总结.mp3', None),
    ]

    def calculate_geometry(self):
        # 数学值
        AC_len = 3.0
        CB_len = 4.0
        AB_len = 5.0

        # 显示缩放因子
        scale = 0.7

        # 显示坐标：三角形放在左侧
        layout_figure = LEFT * 2.5 + DOWN * 0.3
        C_disp = layout_figure + np.array([0.0, 0.0, 0.0])
        A_disp = layout_figure + np.array([0.0, AC_len * scale, 0.0])
        B_disp = layout_figure + np.array([CB_len * scale, 0.0, 0.0])

        # 直角标记位置
        right_angle_size = 0.25
        right_angle_pos = C_disp + np.array([right_angle_size, right_angle_size, 0.0])

        geometry = {
            'points': {
                'A': A_disp,
                'B': B_disp,
                'C': C_disp,
            },
            'lines': {
                'CA': {'start': C_disp, 'end': A_disp, 'length': AC_len * scale},
                'CB': {'start': C_disp, 'end': B_disp, 'length': CB_len * scale},
                'AB': {'start': A_disp, 'end': B_disp, 'length': AB_len * scale},
            },
            'math_lengths': {
                'AC': AC_len,
                'CB': CB_len,
                'AB': AB_len,
            },
            'right_angle': {
                'pos': right_angle_pos,
                'size': right_angle_size,
            },
            'layout': {
                'figure_center': layout_figure,
                'formula_pos': RIGHT * 3.0 + UP * 2.0,
                'calc_pos': RIGHT * 3.0 + DOWN * 0.5,
                'summary_pos': DOWN * 3.0,
            },
        }
        return geometry

    def assert_geometry(self, geometry):
        # 验证勾股定理
        ac = geometry['math_lengths']['AC']
        cb = geometry['math_lengths']['CB']
        ab = geometry['math_lengths']['AB']
        assert abs(ab ** 2 - (ac ** 2 + cb ** 2)) < 1e-6, "Pythagorean theorem failed"
        # 验证画布范围
        self._check_canvas_bounds(geometry)

    def define_elements(self, geometry):
        pts = geometry['points']
        elements = {}

        # 点
        elements['points'] = {
            'A': Dot(pts['A'], color=self.COLORS['highlight'], radius=0.08),
            'B': Dot(pts['B'], color=self.COLORS['highlight'], radius=0.08),
            'C': Dot(pts['C'], color=self.COLORS['highlight'], radius=0.08),
        }

        # 顶点标签
        elements['labels'] = {
            'A': Text('A', font_size=36, color=self.COLORS['text']),
            'B': Text('B', font_size=36, color=self.COLORS['text']),
            'C': Text('C', font_size=36, color=self.COLORS['text']),
        }
        elements['labels']['A'].next_to(pts['A'], UP, buff=0.15)
        elements['labels']['B'].next_to(pts['B'], RIGHT, buff=0.15)
        elements['labels']['C'].next_to(pts['C'], DOWN + LEFT, buff=0.15)

        # 边
        elements['lines'] = {}
        for name, cfg in geometry['lines'].items():
            color = self.COLORS['secondary'] if name == 'AB' else self.COLORS['primary']
            elements['lines'][name] = Line(
                start=cfg['start'], end=cfg['end'],
                color=color, stroke_width=4
            )

        # 直角标记
        ra = geometry['right_angle']
        ra_lines = VGroup()
        ra_lines.add(Line(
            pts['C'] + np.array([ra['size'], 0, 0]),
            pts['C'] + np.array([ra['size'], ra['size'], 0]),
            color=self.COLORS['text'], stroke_width=2
        ))
        ra_lines.add(Line(
            pts['C'] + np.array([0, ra['size'], 0]),
            pts['C'] + np.array([ra['size'], ra['size'], 0]),
            color=self.COLORS['text'], stroke_width=2
        ))
        elements['right_angle_mark'] = ra_lines

        return elements

    def play_scene_1(self, elements, geometry):
        expected = self.start_scene_with_audio(1)
        sub = self.create_subtitle("勾股定理介绍")
        self.play(FadeIn(sub), run_time=0.3)

        # 标题
        title = Text("勾股定理", font_size=72, color=self.COLORS['highlight'])
        title.move_to(UP * 1.5)

        # 副标题
        subtitle = Text("直角三角形ABC，求AB的长度", font_size=32, color=self.COLORS['text'])
        subtitle.next_to(title, DOWN, buff=0.8)

        self.play(Write(title), run_time=1.2)
        self.wait_for_narration("勾股定理")
        self.play(FadeIn(subtitle), run_time=0.8)
        self.wait(0.5)

        # 保存以便后续幕淡出
        self._scene1_elements = VGroup(title, subtitle)
        self.play(FadeOut(sub), run_time=0.3)
        self.end_scene_with_audio(expected)

    def play_scene_2(self, elements, geometry):
        expected = self.start_scene_with_audio(2)
        sub = self.create_subtitle("画直角三角形")
        self.play(FadeIn(sub), run_time=0.3)

        # 淡出第一幕
        self.play(FadeOut(self._scene1_elements), run_time=0.5)

        pts = geometry['points']

        # 画两条直角边
        self.play(Create(elements['lines']['CA']), run_time=1.0)
        self.wait_for_narration("AC等于三")
        self.play(Create(elements['lines']['CB']), run_time=1.0)
        self.wait_for_narration("CB等于四")

        # 画点
        self.play(FadeIn(elements['points']['C']), run_time=0.3)

        # 显示直角标记
        self.play(Create(elements['right_angle_mark']), run_time=0.5)
        self.wait_for_narration("九十度")

        # 显示顶点标签
        self.play(
            FadeIn(elements['labels']['C']),
            run_time=0.4
        )

        self.play(FadeOut(sub), run_time=0.3)
        self.end_scene_with_audio(expected)

    def play_scene_3(self, elements, geometry):
        expected = self.start_scene_with_audio(3)
        sub = self.create_subtitle("标注直角边和斜边")
        self.play(FadeIn(sub), run_time=0.3)

        pts = geometry['points']

        # 显示点A和B
        self.play(
            FadeIn(elements['points']['A']),
            FadeIn(elements['points']['B']),
            run_time=0.5
        )
        self.play(
            FadeIn(elements['labels']['A']),
            FadeIn(elements['labels']['B']),
            run_time=0.5
        )

        # 画斜边
        self.play(Create(elements['lines']['AB']), run_time=1.2)

        # 标注边长
        ac_label = MathTex(r"AC = 3", font_size=36, color=self.COLORS['primary'])
        ac_label.next_to(elements['lines']['CA'], LEFT, buff=0.3)

        cb_label = MathTex(r"CB = 4", font_size=36, color=self.COLORS['primary'])
        cb_label.next_to(elements['lines']['CB'], DOWN, buff=0.3)

        ab_label = MathTex(r"AB = ?", font_size=36, color=self.COLORS['secondary'])
        ab_label.move_to(elements['lines']['AB'].get_center() + UP * 0.4 + LEFT * 0.3)

        self.play(Write(ac_label), run_time=0.8)
        self.wait_for_narration("直角边")
        self.play(Write(cb_label), run_time=0.8)
        self.play(Write(ab_label), run_time=0.8)
        self.wait_for_narration("斜边")

        self._scene3_extra = VGroup(ac_label, cb_label, ab_label)

        self.play(FadeOut(sub), run_time=0.3)
        self.end_scene_with_audio(expected)

    def play_scene_4(self, elements, geometry):
        expected = self.start_scene_with_audio(4)
        sub = self.create_subtitle("勾股定理公式")
        self.play(FadeIn(sub), run_time=0.3)

        # 公式写在右侧
        formula = MathTex(
            r"AB^2 = AC^2 + CB^2",
            font_size=48,
            color=self.COLORS['highlight']
        )
        formula.move_to(geometry['layout']['formula_pos'])

        self.play(Write(formula), run_time=1.2)
        self.wait_for_narration("勾股定理")
        self.wait_for_narration("AB的平方")

        # 框出公式
        box = SurroundingRectangle(formula, color=self.COLORS['highlight'], buff=0.2)
        self.play(Create(box), run_time=0.6)

        self._formula_box = VGroup(formula, box)

        self.play(FadeOut(sub), run_time=0.3)
        self.end_scene_with_audio(expected)

    def play_scene_5(self, elements, geometry):
        expected = self.start_scene_with_audio(5)
        sub = self.create_subtitle("代入数值计算")
        self.play(FadeIn(sub), run_time=0.3)

        calc_pos = geometry['layout']['calc_pos']

        # 步骤1: 代入
        step1 = MathTex(
            r"AB^2 = 3^2 + 4^2",
            font_size=42,
            color=self.COLORS['text']
        )
        step1.move_to(calc_pos + UP * 1.5)
        self.play(Write(step1), run_time=1.0)
        self.wait_for_narration("代入数值")

        # 步骤2: 计算
        step2 = MathTex(
            r"AB^2 = 9 + 16 = 25",
            font_size=42,
            color=self.COLORS['text']
        )
        step2.move_to(calc_pos + UP * 0.3)
        self.play(Write(step2), run_time=1.0)

        # 步骤3: 开方
        step3 = MathTex(
            r"AB = \sqrt{25} = 5",
            font_size=44,
            color=self.COLORS['highlight']
        )
        step3.move_to(calc_pos + DOWN * 0.9)
        self.play(Write(step3), run_time=1.2)
        self.wait_for_narration("等于五")

        # 更新 AB 标签
        ab_label = MathTex(r"AB = 5", font_size=36, color=self.COLORS['secondary'])
        ab_label.move_to(elements['lines']['AB'].get_center() + UP * 0.4 + LEFT * 0.3)
        self.play(Transform(self._scene3_extra[2], ab_label), run_time=0.8)

        self._calc_elements = VGroup(step1, step2, step3)

        self.play(FadeOut(sub), run_time=0.3)
        self.end_scene_with_audio(expected)

    def play_scene_6(self, elements, geometry):
        expected = self.start_scene_with_audio(6)
        sub = self.create_subtitle("答案：AB = 5")
        self.play(FadeIn(sub), run_time=0.3)

        # 高亮最终结果
        self.highlight_element(self._calc_elements[2], color=self.COLORS['highlight'], scale=1.2, duration=1.0)

        # 显示总结
        summary = MathTex(
            r"AB = 5",
            font_size=64,
            color=self.COLORS['highlight']
        )
        summary.move_to(geometry['layout']['summary_pos'])
        box = SurroundingRectangle(summary, color=self.COLORS['highlight'], buff=0.3)
        result = VGroup(summary, box)

        self.play(Write(result), run_time=1.2)
        self.wait_for_narration("长度是五")

        # 高亮整个三角形
        triangle_group = VGroup(
            elements['lines']['CA'],
            elements['lines']['CB'],
            elements['lines']['AB'],
        )
        self.highlight_element(triangle_group, color=self.COLORS['highlight'], scale=1.05, duration=0.8)

        self.wait(0.5)
        self.play(FadeOut(sub), run_time=0.3)
        self.end_scene_with_audio(expected)
