# Auto-generated by Claude Code Generation Mode
# Record ID: 48
# Generated at: 2026-07-05 16:46:51

from manim import *
import numpy as np
import math
import sys
import os

# 添加项目根目录到路径
sys.path.insert(0, r"C:\Users\lxy\WorkBuddy\2026-06-30-16-26-23\education_agent")

# 设置音频目录环境变量（使用绝对路径）
os.environ["MATHANIM_AUDIO_DIR"] = r"C:\Users\lxy\WorkBuddy\2026-06-30-16-26-23\education_agent\output\audio\run_20260705_164642"
os.environ["MATHANIM_VIDEO_OUTPUT"] = r"C:\Users\lxy\WorkBuddy\2026-06-30-16-26-23\education_agent\output\videos"

# 导入基类
from animation.base_scene import MathAnimScene

# 设置渲染参数
config.pixel_width = 1920
config.pixel_height = 1080
config.frame_rate = 60

from manim import *
import numpy as np

class MathProblemScene(MathAnimScene):
    SCENES = [
        (1, "开场", "audio_001_开场.mp3", None),
        (2, "画三角形", "audio_002_画三角形.mp3", None),
        (3, "标注边长", "audio_003_标注边长.mp3", None),
        (4, "应用勾股定理", "audio_004_应用勾股定理.mp3", None),
        (5, "计算结果", "audio_005_计算结果.mp3", None),
        (6, "总结", "audio_006_总结.mp3", None),
    ]

    def calculate_geometry(self):
        # Math values
        AC_math = 3.0
        CB_math = 4.0
        AB_math = 5.0

        # Scale factor to fit on canvas
        # AB display length should be about 6 units to look good
        scale = 1.2
        AC_disp = AC_math * scale  # 3.6
        CB_disp = CB_math * scale  # 4.8
        AB_disp = AB_math * scale  # 6.0

        # Place C at origin, A above C, B to the right of C
        C = np.array([0, 0, 0])
        A = np.array([0, AC_disp, 0])  # straight up from C
        B = np.array([CB_disp, 0, 0])  # to the right of C

        # Verify AB length
        AB_check = np.linalg.norm(B - A)

        geometry = {
            'points': {
                'A': A,
                'B': B,
                'C': C,
            },
            'lines': {
                'AB': {'start': A, 'end': B, 'length': AB_check},
                'AC': {'start': A, 'end': C, 'length': AC_disp},
                'BC': {'start': B, 'end': C, 'length': CB_disp},
            },
            'circles': {},
            'angles': {
                'C': {'value': np.pi / 2, 'deg': 90.0},
            },
            'math': {
                'AC': AC_math,
                'CB': CB_math,
                'AB': AB_math,
                'AC_squared': 9,
                'CB_squared': 16,
                'sum_squares': 25,
            },
        }
        return geometry

    def assert_geometry(self, geometry):
        pts = geometry['points']
        A, B, C = pts['A'], pts['B'], pts['C']

        # Verify AC = 3, CB = 4, AB = 5 (display values scaled)
        AC_disp = np.linalg.norm(A - C)
        CB_disp = np.linalg.norm(B - C)
        AB_disp = np.linalg.norm(B - A)

        assert abs(AC_disp - 3.6) < 0.01, f"AC display length should be 3.6, got {AC_disp}"
        assert abs(CB_disp - 4.8) < 0.01, f"CB display length should be 4.8, got {CB_disp}"
        assert abs(AB_disp - 6.0) < 0.01, f"AB display length should be 6.0, got {AB_disp}"

        # Verify angle C = 90 degrees
        CA = A - C
        CB = B - C
        cos_C = np.dot(CA, CB) / (np.linalg.norm(CA) * np.linalg.norm(CB))
        assert abs(cos_C) < 1e-6, f"Angle C should be 90 degrees, cos = {cos_C}"

        # Verify Pythagorean theorem holds
        assert abs(AB_disp**2 - AC_disp**2 - CB_disp**2) < 0.01, "Pythagorean theorem violated"

        self._check_canvas_bounds(geometry)

    def define_elements(self, geometry):
        pts = geometry['points']
        lines_cfg = geometry['lines']

        elements = {
            'points': {},
            'lines': {},
            'labels': {},
            'right_angle': None,
        }

        # Create points (dots)
        for name, pos in pts.items():
            dot = Dot(pos, color=self.COLORS['highlight'], radius=0.08)
            elements['points'][name] = dot

        # Create lines
        for name, cfg in lines_cfg.items():
            line = Line(
                start=cfg['start'],
                end=cfg['end'],
                color=self.COLORS['primary'],
                stroke_width=3,
            )
            elements['lines'][name] = line

        # Create labels
        label_colors = {'A': self.COLORS['angle_a'], 'B': self.COLORS['angle_b'], 'C': self.COLORS['angle_c']}
        label_positions = {
            'A': pts['A'] + np.array([-0.3, 0.2, 0]),
            'B': pts['B'] + np.array([0.3, -0.3, 0]),
            'C': pts['C'] + np.array([-0.3, -0.3, 0]),
        }
        for name, pos in label_positions.items():
            label = Text(name, font_size=32, color=label_colors[name])
            label.move_to(pos)
            elements['labels'][name] = label

        # Right angle marker at C
        C = pts['C']
        A = pts['A']
        B = pts['B']
        # Small square at C
        CA_dir = (A - C) / np.linalg.norm(A - C)
        CB_dir = (B - C) / np.linalg.norm(B - C)
        size = 0.3
        p1 = C + CA_dir * size
        p2 = C + CA_dir * size + CB_dir * size
        p3 = C + CB_dir * size
        right_angle = Polygon(p1, p2, p3, color=self.COLORS['text'], stroke_width=2, fill_opacity=0)
        elements['right_angle'] = right_angle

        return elements

    def play_scene_1(self, elements, geometry):
        expected = self.start_scene_with_audio(1)

        sub = self.create_subtitle("勾股定理应用")
        self.play(FadeIn(sub), run_time=0.5)

        # Title
        title = Text("直角三角形ABC", font_size=48, color=self.COLORS['highlight'])
        title.move_to(np.array([0, 1.5, 0]))
        subtitle = Text("角C等于90度，求AB的长度", font_size=28, color=self.COLORS['text'])
        subtitle.move_to(np.array([0, 0.3, 0]))

        self.play(Write(title), run_time=1.2)
        self.wait_for_narration("勾股定理")
        self.play(FadeIn(subtitle), run_time=0.8)
        self.wait_for_narration("应用")

        self.play(FadeOut(title), FadeOut(subtitle), FadeOut(sub), run_time=0.5)
        self.end_scene_with_audio(expected)

    def play_scene_2(self, elements, geometry):
        self.clear()
        expected = self.start_scene_with_audio(2)

        sub = self.create_subtitle("画直角三角形")
        self.play(FadeIn(sub), run_time=0.5)

        # Draw triangle lines one by one
        self.play(Create(elements['lines']['AC']), run_time=1.0)
        self.wait_for_narration("直角三角形")

        self.play(Create(elements['lines']['BC']), run_time=1.0)
        self.wait_for_narration("角C是直角")

        self.play(Create(elements['lines']['AB']), run_time=1.2)

        # Show right angle marker
        self.play(Create(elements['right_angle']), run_time=0.5)

        # Show vertex labels
        self.play(
            FadeIn(elements['labels']['A']),
            FadeIn(elements['labels']['B']),
            FadeIn(elements['labels']['C']),
            run_time=0.6
        )

        # Show point dots
        self.play(
            FadeIn(elements['points']['A']),
            FadeIn(elements['points']['B']),
            FadeIn(elements['points']['C']),
            run_time=0.4
        )

        self.wait_for_narration("直角")
        self.play(FadeOut(sub), run_time=0.5)
        self.end_scene_with_audio(expected)

    def play_scene_3(self, elements, geometry):
        self.clear()
        expected = self.start_scene_with_audio(3)

        sub = self.create_subtitle("标注已知边长")
        self.play(FadeIn(sub), run_time=0.5)

        # Re-create triangle elements
        C = geometry['points']['C']
        A = geometry['points']['A']
        B = geometry['points']['B']

        line_AB = Line(start=A, end=B, color=self.COLORS['primary'], stroke_width=3)
        line_AC = Line(start=A, end=C, color=self.COLORS['primary'], stroke_width=3)
        line_BC = Line(start=B, end=C, color=self.COLORS['primary'], stroke_width=3)

        dot_A = Dot(A, color=self.COLORS['highlight'], radius=0.08)
        dot_B = Dot(B, color=self.COLORS['highlight'], radius=0.08)
        dot_C = Dot(C, color=self.COLORS['highlight'], radius=0.08)

        label_A = Text("A", font_size=32, color=self.COLORS['angle_a']).move_to(A + np.array([-0.3, 0.2, 0]))
        label_B = Text("B", font_size=32, color=self.COLORS['angle_b']).move_to(B + np.array([0.3, -0.3, 0]))
        label_C = Text("C", font_size=32, color=self.COLORS['angle_c']).move_to(C + np.array([-0.3, -0.3, 0]))

        # Right angle marker
        CA_dir = (A - C) / np.linalg.norm(A - C)
        CB_dir = (B - C) / np.linalg.norm(B - C)
        size = 0.3
        p1 = C + CA_dir * size
        p2 = C + CA_dir * size + CB_dir * size
        p3 = C + CB_dir * size
        right_angle = Polygon(p1, p2, p3, color=self.COLORS['text'], stroke_width=2, fill_opacity=0)

        # Draw everything
        self.play(Create(line_AC), Create(line_BC), Create(line_AB), run_time=1.5)
        self.play(Create(right_angle), run_time=0.4)
        self.play(FadeIn(dot_A), FadeIn(dot_B), FadeIn(dot_C), run_time=0.4)
        self.play(FadeIn(label_A), FadeIn(label_B), FadeIn(label_C), run_time=0.4)

        # Label AC = 3
        AC_mid = (A + C) / 2 + np.array([-0.5, 0, 0])
        ac_label = MathTex(r"AC = 3", font_size=32, color=self.COLORS['secondary'])
        ac_label.move_to(AC_mid)
        self.play(Write(ac_label), run_time=0.8)
        self.wait_for_narration("AC")

        # Label CB = 4
        CB_mid = (C + B) / 2 + np.array([0, -0.5, 0])
        cb_label = MathTex(r"CB = 4", font_size=32, color=self.COLORS['secondary'])
        cb_label.move_to(CB_mid)
        self.play(Write(cb_label), run_time=0.8)
        self.wait_for_narration("等于4")

        # Question mark for AB
        AB_mid = (A + B) / 2 + np.array([0.3, 0.3, 0])
        ab_label = MathTex(r"AB = ?", font_size=36, color=self.COLORS['highlight'])
        ab_label.move_to(AB_mid)
        self.play(Write(ab_label), run_time=0.8)
        self.wait_for_narration("斜边AB")

        self.play(FadeOut(sub), run_time=0.5)
        self.end_scene_with_audio(expected)

    def play_scene_4(self, elements, geometry):
        self.clear()
        expected = self.start_scene_with_audio(4)

        sub = self.create_subtitle("应用勾股定理")
        self.play(FadeIn(sub), run_time=0.5)

        # Re-display triangle
        C = geometry['points']['C']
        A = geometry['points']['A']
        B = geometry['points']['B']

        line_AB = Line(start=A, end=B, color=self.COLORS['primary'], stroke_width=3)
        line_AC = Line(start=A, end=C, color=self.COLORS['primary'], stroke_width=3)
        line_BC = Line(start=B, end=C, color=self.COLORS['primary'], stroke_width=3)

        dot_A = Dot(A, color=self.COLORS['highlight'], radius=0.08)
        dot_B = Dot(B, color=self.COLORS['highlight'], radius=0.08)
        dot_C = Dot(C, color=self.COLORS['highlight'], radius=0.08)

        label_A = Text("A", font_size=32, color=self.COLORS['angle_a']).move_to(A + np.array([-0.3, 0.2, 0]))
        label_B = Text("B", font_size=32, color=self.COLORS['angle_b']).move_to(B + np.array([0.3, -0.3, 0]))
        label_C = Text("C", font_size=32, color=self.COLORS['angle_c']).move_to(C + np.array([-0.3, -0.3, 0]))

        self.play(Create(line_AC), Create(line_BC), Create(line_AB), run_time=1.5)
        self.play(FadeIn(dot_A), FadeIn(dot_B), FadeIn(dot_C), run_time=0.4)
        self.play(FadeIn(label_A), FadeIn(label_B), FadeIn(label_C), run_time=0.4)

        # Pythagorean theorem formula
        formula = MathTex(r"AB^2 = AC^2 + CB^2", font_size=44, color=self.COLORS['highlight'])
        formula.move_to(np.array([0, 3.2, 0]))

        self.play(Write(formula), run_time=1.5)
        self.wait_for_narration("勾股定理")
        self.wait_for_narration("平方")

        # Highlight each part
        ac_box = SurroundingRectangle(formula[0][3:6], color=self.COLORS['secondary'], buff=0.05)
        self.play(Create(ac_box), run_time=0.5)
        self.wait_for_narration("AC")
        self.play(FadeOut(ac_box), run_time=0.3)

        cb_box = SurroundingRectangle(formula[0][7:10], color=self.COLORS['secondary'], buff=0.05)
        self.play(Create(cb_box), run_time=0.5)
        self.wait_for_narration("CB")
        self.play(FadeOut(cb_box), run_time=0.3)

        self.play(FadeOut(sub), run_time=0.5)
        self.end_scene_with_audio(expected)

    def play_scene_5(self, elements, geometry):
        self.clear()
        expected = self.start_scene_with_audio(5)

        sub = self.create_subtitle("计算AB长度")
        self.play(FadeIn(sub), run_time=0.5)

        # Re-display triangle
        C = geometry['points']['C']
        A = geometry['points']['A']
        B = geometry['points']['B']

        line_AB = Line(start=A, end=B, color=self.COLORS['primary'], stroke_width=3)
        line_AC = Line(start=A, end=C, color=self.COLORS['primary'], stroke_width=3)
        line_BC = Line(start=B, end=C, color=self.COLORS['primary'], stroke_width=3)

        dot_A = Dot(A, color=self.COLORS['highlight'], radius=0.08)
        dot_B = Dot(B, color=self.COLORS['highlight'], radius=0.08)
        dot_C = Dot(C, color=self.COLORS['highlight'], radius=0.08)

        label_A = Text("A", font_size=32, color=self.COLORS['angle_a']).move_to(A + np.array([-0.3, 0.2, 0]))
        label_B = Text("B", font_size=32, color=self.COLORS['angle_b']).move_to(B + np.array([0.3, -0.3, 0]))
        label_C = Text("C", font_size=32, color=self.COLORS['angle_c']).move_to(C + np.array([-0.3, -0.3, 0]))

        self.play(Create(line_AC), Create(line_BC), Create(line_AB), run_time=1.5)
        self.play(FadeIn(dot_A), FadeIn(dot_B), FadeIn(dot_C), run_time=0.4)
        self.play(FadeIn(label_A), FadeIn(label_B), FadeIn(label_C), run_time=0.4)

        # Step-by-step calculation
        step1 = MathTex(r"AB^2 = 3^2 + 4^2", font_size=40, color=self.COLORS['text'])
        step1.move_to(np.array([0, 3.2, 0]))
        self.play(Write(step1), run_time=1.2)
        self.wait_for_narration("代入")

        step2 = MathTex(r"AB^2 = 9 + 16", font_size=40, color=self.COLORS['text'])
        step2.move_to(np.array([0, 2.3, 0]))
        self.play(Transform(step1, step2), run_time=1.0)
        self.wait_for_narration("等于25")

        step3 = MathTex(r"AB = 5", font_size=48, color=self.COLORS['highlight'])
        step3.move_to(np.array([0, 1.2, 0]))
        self.play(Write(step3), run_time=1.0)
        self.wait_for_narration("等于5")

        # Highlight AB on triangle
        self.play(
            line_AB.animate.set_color(self.COLORS['highlight']).set_stroke(width=5),
            run_time=1.0
        )

        # Add AB = 5 label
        AB_mid = (A + B) / 2 + np.array([0.3, 0.3, 0])
        ab_label = MathTex(r"AB = 5", font_size=32, color=self.COLORS['highlight'])
        ab_label.move_to(AB_mid)
        self.play(Write(ab_label), run_time=0.8)

        self.play(FadeOut(sub), run_time=0.5)
        self.end_scene_with_audio(expected)

    def play_scene_6(self, elements, geometry):
        self.clear()
        expected = self.start_scene_with_audio(6)

        sub = self.create_subtitle("结论总结")
        self.play(FadeIn(sub), run_time=0.5)

        # Re-display final state
        C = geometry['points']['C']
        A = geometry['points']['A']
        B = geometry['points']['B']

        line_AB = Line(start=A, end=B, color=self.COLORS['highlight'], stroke_width=5)
        line_AC = Line(start=A, end=C, color=self.COLORS['primary'], stroke_width=3)
        line_BC = Line(start=B, end=C, color=self.COLORS['primary'], stroke_width=3)

        dot_A = Dot(A, color=self.COLORS['highlight'], radius=0.08)
        dot_B = Dot(B, color=self.COLORS['highlight'], radius=0.08)
        dot_C = Dot(C, color=self.COLORS['highlight'], radius=0.08)

        label_A = Text("A", font_size=32, color=self.COLORS['angle_a']).move_to(A + np.array([-0.3, 0.2, 0]))
        label_B = Text("B", font_size=32, color=self.COLORS['angle_b']).move_to(B + np.array([0.3, -0.3, 0]))
        label_C = Text("C", font_size=32, color=self.COLORS['angle_c']).move_to(C + np.array([-0.3, -0.3, 0]))

        # Right angle marker
        CA_dir = (A - C) / np.linalg.norm(A - C)
        CB_dir = (B - C) / np.linalg.norm(B - C)
        size = 0.3
        p1 = C + CA_dir * size
        p2 = C + CA_dir * size + CB_dir * size
        p3 = C + CB_dir * size
        right_angle = Polygon(p1, p2, p3, color=self.COLORS['text'], stroke_width=2, fill_opacity=0)

        self.play(Create(line_AC), Create(line_BC), Create(line_AB), run_time=1.5)
        self.play(Create(right_angle), run_time=0.4)
        self.play(FadeIn(dot_A), FadeIn(dot_B), FadeIn(dot_C), run_time=0.4)
        self.play(FadeIn(label_A), FadeIn(label_B), FadeIn(label_C), run_time=0.4)

        # Final answer prominently displayed
        AB_mid = (A + B) / 2 + np.array([0.3, 0.3, 0])
        ab_label = MathTex(r"AB = 5", font_size=36, color=self.COLORS['highlight'])
        ab_label.move_to(AB_mid)
        self.play(Write(ab_label), run_time=0.8)

        # Final summary
        conclusion = MathTex(r"AB = \sqrt{AC^2 + CB^2} = \sqrt{9 + 16} = 5", font_size=36, color=self.COLORS['highlight'])
        conclusion.move_to(np.array([0, 3.3, 0]))
        self.play(Write(conclusion), run_time=1.5)
        self.wait_for_narration("勾三股四弦五")

        # Pulse AB line
        self.play(
            line_AB.animate.scale(1.05).set_stroke(width=6),
            run_time=0.5
        )
        self.play(
            line_AB.animate.scale(1/1.05).set_stroke(width=5),
            run_time=0.5
        )

        # Key insight
        insight = Text("勾三股四弦五", font_size=36, color=self.COLORS['highlight'])
        insight.move_to(np.array([0, -3.0, 0]))
        self.play(Write(insight), run_time=1.0)
        self.wait_for_narration("5")

        self.play(FadeOut(sub), FadeOut(conclusion), FadeOut(insight), run_time=0.8)
        self.end_scene_with_audio(expected)
