# Auto-generated by Claude Code Generation Mode
# Record ID: 37
# Generated at: 2026-07-05 01:04:07

from manim import *
import numpy as np
import sys
import os

# 添加项目根目录到路径
sys.path.insert(0, r"C:\Users\lxy\WorkBuddy\2026-06-30-16-26-23\education_agent")

# 设置音频目录环境变量
os.environ["MATHANIM_AUDIO_DIR"] = r"./output\audio\run_20260705_010353"
os.environ["MATHANIM_VIDEO_OUTPUT"] = r"./output\videos"

# 导入基类
from animation.base_scene import MathAnimScene

# 设置渲染参数
config.pixel_width = 1920
config.pixel_height = 1080
config.frame_rate = 60

import numpy as np
from manim import *


class MathProblemScene(MathAnimScene):
    
    SCENES = [
        (1, "开场", "audio_001_开场.mp3", None),
        (2, "画圆", "audio_002_画圆.mp3", None),
        (3, "标注半径", "audio_003_标注半径.mp3", None),
        (4, "展示公式", "audio_004_展示公式.mp3", None),
        (5, "代入计算", "audio_005_代入计算.mp3", None),
        (6, "总结", "audio_006_总结.mp3", None),
    ]

    def calculate_geometry(self):
        radius = 5.0
        # 为了在画布中显示，使用显示半径（视觉缩放）
        display_radius = 2.2
        center = np.array([0.0, 0.0, 0.0])
        
        # 圆心 O
        O = center.copy()
        
        # 圆周上的关键点
        A = center + np.array([display_radius, 0.0, 0.0])  # 右侧点
        B = center + np.array([0.0, display_radius, 0.0])  # 上方点
        C = center + np.array([-display_radius, 0.0, 0.0])  # 左侧点
        D = center + np.array([0.0, -display_radius, 0.0])  # 下方点
        
        # 半径线段终点（在半径线上选择一点用于标注）
        radius_label_pos = center + np.array([display_radius * 0.5, display_radius * 0.1, 0.0])
        
        geometry = {
            'radius': radius,
            'display_radius': display_radius,
            'center': center,
            'points': {
                'O': O,
                'A': A,
                'B': B,
                'C': C,
                'D': D,
            },
            'lines': {
                'OA': (O, A),
            },
            'radius_label_pos': radius_label_pos,
            'area': radius ** 2 * np.pi,  # 25π ≈ 78.54
        }
        return geometry

    def assert_geometry(self, geometry):
        radius = geometry['radius']
        # 验证半径为5
        assert radius == 5.0, f"半径应为5，实际为{radius}"
        # 验证面积公式
        expected_area = np.pi * radius ** 2
        assert abs(geometry['area'] - expected_area) < 0.01, "面积计算错误"
        # 检查画布范围
        self._check_canvas_bounds(geometry)
        # 验证关键点距离
        dist_OA = np.linalg.norm(geometry['points']['A'] - geometry['center'])
        assert abs(dist_OA - 2.2) < 0.01, "显示半径应约为2.2"

    def define_elements(self, geometry):
        elements = {}
        
        # 创建圆
        circle = Circle(
            radius=geometry['display_radius'],
            color=self.COLORS['primary'],
            stroke_width=4,
        )
        elements['circle'] = circle
        
        # 圆心 O
        center_dot = Dot(
            geometry['points']['O'],
            color=self.COLORS['highlight'],
            radius=0.08,
        )
        elements['center_dot'] = center_dot
        
        # 圆周上的点 A
        point_A = Dot(
            geometry['points']['A'],
            color=self.COLORS['secondary'],
            radius=0.08,
        )
        elements['point_A'] = point_A
        
        # 半径线 OA
        radius_line = Line(
            geometry['points']['O'],
            geometry['points']['A'],
            color=self.COLORS['secondary'],
            stroke_width=3,
        )
        elements['radius_line'] = radius_line
        
        # 圆心标签 O
        label_O = Text("O", font_size=36, color=self.COLORS['highlight'])
        label_O.next_to(geometry['points']['O'], DOWN + LEFT, buff=0.15)
        elements['label_O'] = label_O
        
        # 点A标签
        label_A = Text("A", font_size=36, color=self.COLORS['secondary'])
        label_A.next_to(geometry['points']['A'], RIGHT, buff=0.15)
        elements['label_A'] = label_A
        
        # 半径标签 r=5
        label_r = MathTex(r"r = 5", font_size=40, color=self.COLORS['highlight'])
        label_r.move_to(geometry['radius_label_pos'])
        elements['label_r'] = label_r
        
        # 面积公式 S = πr²
        formula = MathTex(r"S = \pi r^2", font_size=52, color=self.COLORS['highlight'])
        formula.move_to(np.array([0.0, 2.8, 0.0]))
        elements['formula'] = formula
        
        # 代入步骤 S = π × 5²
        formula_sub = MathTex(r"S = \pi \times 5^2", font_size=44, color=self.COLORS['text'])
        formula_sub.move_to(np.array([0.0, 2.8, 0.0]))
        elements['formula_sub'] = formula_sub
        
        # 计算结果 S = 25π
        result = MathTex(r"S = 25\pi", font_size=52, color=self.COLORS['highlight'])
        result.move_to(np.array([0.0, 2.8, 0.0]))
        elements['result'] = result
        
        # 数值结果 ≈ 78.5
        result_num = MathTex(r"\approx 78.5", font_size=40, color=self.COLORS['text'])
        result_num.move_to(np.array([0.0, 2.0, 0.0]))
        elements['result_num'] = result_num
        
        # 标题
        title = Text("求圆的面积", font_size=56, color=self.COLORS['highlight'])
        title.move_to(np.array([0.0, 0.0, 0.0]))
        elements['title'] = title
        
        # 副标题 - 已知条件
        subtitle = Text("已知：半径 r = 5", font_size=36, color=self.COLORS['text'])
        subtitle.move_to(np.array([0.0, -1.0, 0.0]))
        elements['subtitle'] = subtitle
        
        # 结论文本
        conclusion = Text("圆的面积 S = 25π", font_size=44, color=self.COLORS['highlight'])
        conclusion.move_to(np.array([0.0, -2.5, 0.0]))
        elements['conclusion'] = conclusion
        
        return elements

    def play_scene_1(self, elements, geometry):
        expected = self.start_scene_with_audio(1)
        
        # 显示标题
        self.play(Write(elements['title']), run_time=1.2)
        self.wait_for_narration("求圆的面积")
        
        # 显示副标题/已知条件
        self.play(FadeIn(elements['subtitle'], shift=UP * 0.3), run_time=0.8)
        self.wait_for_narration("半径是五")
        
        # 短暂停留后清除标题区域
        self.wait(0.5)
        
        self.end_scene_with_audio(expected)

    def play_scene_2(self, elements, geometry):
        expected = self.start_scene_with_audio(2)
        
        # 清除标题区域
        self.play(
            FadeOut(elements['title']),
            FadeOut(elements['subtitle']),
            run_time=0.6
        )
        
        # 绘制圆
        self.play(Create(elements['circle']), run_time=1.8)
        self.wait_for_narration("画一个半径为五的圆")
        
        # 标记圆心
        self.play(
            FadeIn(elements['center_dot'], scale=1.5),
            run_time=0.5
        )
        self.play(Write(elements['label_O']), run_time=0.5)
        self.wait_for_narration("圆心标记为O")
        
        # 标记圆周上的点A
        self.play(
            FadeIn(elements['point_A'], scale=1.5),
            run_time=0.5
        )
        self.play(Write(elements['label_A']), run_time=0.5)
        
        self.end_scene_with_audio(expected)

    def play_scene_3(self, elements, geometry):
        expected = self.start_scene_with_audio(3)
        
        # 画半径线
        self.play(Create(elements['radius_line']), run_time=1.0)
        self.wait_for_narration("标注出半径")
        
        # 标注 r = 5
        self.play(Write(elements['label_r']), run_time=0.8)
        self.wait_for_narration("r等于五")
        
        # 高亮半径
        self.highlight_element(elements['radius_line'], color=self.COLORS['highlight'], scale=1.2, duration=0.8)
        
        self.end_scene_with_audio(expected)

    def play_scene_4(self, elements, geometry):
        expected = self.start_scene_with_audio(4)
        
        # 移开标注（稍微上移），展示公式
        self.play(
            elements['label_r'].animate.move_to(np.array([geometry['display_radius'] * 0.5, geometry['display_radius'] * 0.3, 0.0])),
            run_time=0.6
        )
        
        # 显示面积公式
        self.play(Write(elements['formula']), run_time=1.2)
        self.wait_for_narration("S等于π乘以r的平方")
        
        # 高亮公式
        self.highlight_element(elements['formula'], color=self.COLORS['secondary'], scale=1.15, duration=1.0)
        
        self.end_scene_with_audio(expected)

    def play_scene_5(self, elements, geometry):
        expected = self.start_scene_with_audio(5)
        
        # 公式变换为代入形式
        self.play(
            Transform(elements['formula'], elements['formula_sub']),
            run_time=1.0
        )
        self.wait_for_narration("将半径r等于五代入公式")
        
        # 变为最终结果
        self.play(
            Transform(elements['formula'], elements['result']),
            run_time=1.2
        )
        self.wait_for_narration("等于二十五π")
        
        # 高亮结果
        self.highlight_element(elements['formula'], color=self.COLORS['highlight'], scale=1.2, duration=1.0)
        
        self.end_scene_with_audio(expected)

    def play_scene_6(self, elements, geometry):
        expected = self.start_scene_with_audio(6)
        
        # 显示数值结果
        self.play(Write(elements['result_num']), run_time=0.8)
        self.wait_for_narration("约等于七十八点五")
        
        # 显示结论
        self.play(Write(elements['conclusion']), run_time=1.0)
        self.wait_for_narration("圆的面积是二十五π")
        
        # 最终高亮整个图形
        self.highlight_element(elements['circle'], color=self.COLORS['highlight'], scale=1.05, duration=0.8)
        
        self.end_scene_with_audio(expected)
