# Auto-generated by Claude Code Generation Mode
# Record ID: 41
# Generated at: 2026-07-05 02:03:35

from manim import *
import numpy as np
import math
import sys
import os

# 添加项目根目录到路径
sys.path.insert(0, r"C:\Users\lxy\WorkBuddy\2026-06-30-16-26-23\education_agent")

# 设置音频目录环境变量（使用绝对路径）
os.environ["MATHANIM_AUDIO_DIR"] = r"C:\Users\lxy\WorkBuddy\2026-06-30-16-26-23\education_agent\output\audio\run_20260705_020322"
os.environ["MATHANIM_VIDEO_OUTPUT"] = r"C:\Users\lxy\WorkBuddy\2026-06-30-16-26-23\education_agent\output\videos"

# 导入基类
from animation.base_scene import MathAnimScene

# 设置渲染参数
config.pixel_width = 1920
config.pixel_height = 1080
config.frame_rate = 60

import numpy as np
from manim import *


class MathProblemScene(MathAnimScene):

    SCENES = [
        (1, "开场", "audio_001_开场.mp3", None),
        (2, "画圆", "audio_002_画圆.mp3", None),
        (3, "标注半径", "audio_003_标注半径.mp3", None),
        (4, "推导公式", "audio_004_推导公式.mp3", None),
        (5, "代入计算", "audio_005_代入计算.mp3", None),
        (6, "总结", "audio_006_总结.mp3", None),
    ]

    def calculate_geometry(self):
        display_radius = 2.0
        center = np.array([0.0, 0.0, 0.0])

        points = {
            'O': center,
        }

        circle_points = []
        n_points = 60
        for i in range(n_points):
            angle = 2 * np.pi * i / n_points
            x = center[0] + display_radius * np.cos(angle)
            y = center[1] + display_radius * np.sin(angle)
            circle_points.append(np.array([x, y, 0.0]))

        endpoint_angle = np.pi / 4
        radius_end = np.array([
            center[0] + display_radius * np.cos(endpoint_angle),
            center[1] + display_radius * np.sin(endpoint_angle),
            0.0
        ])

        geometry = {
            'center': center,
            'display_radius': display_radius,
            'radius': 5,
            'area_value': 25,
            'area_approx': 25 * np.pi,
            'points': points,
            'circle_points': circle_points,
            'radius_end': radius_end,
            'endpoint_angle': endpoint_angle,
        }
        return geometry

    def assert_geometry(self, geometry):
        radius = geometry['radius']
        assert radius == 5, "题目给定半径应为5"
        display_radius = geometry['display_radius']
        assert display_radius <= 3.0, "显示半径应在画布范围内"
        self._check_canvas_bounds(geometry)
        print("[OK] Geometry validation passed: radius=5, area=25*pi")

    def define_elements(self, geometry):
        elements = {}

        elements['circle'] = Circle(
            radius=geometry['display_radius'],
            color=self.COLORS['primary'],
            stroke_width=4,
        )
        elements['circle'].move_to(geometry['center'])

        elements['center_dot'] = Dot(
            point=geometry['center'],
            radius=0.08,
            color=self.COLORS['highlight'],
        )

        elements['center_label'] = Text("O", font_size=32, color=self.COLORS['text'])
        elements['center_label'].move_to(geometry['center'] + np.array([-0.25, -0.25, 0.0]))

        elements['radius_line'] = Line(
            geometry['center'],
            geometry['radius_end'],
            color=self.COLORS['secondary'],
            stroke_width=4,
        )

        elements['radius_end_dot'] = Dot(
            point=geometry['radius_end'],
            radius=0.06,
            color=self.COLORS['secondary'],
        )

        elements['radius_label'] = Text("r", font_size=32, color=self.COLORS['secondary'])
        mid_r = (geometry['center'] + geometry['radius_end']) / 2
        elements['radius_label'].move_to(mid_r + np.array([0.2, 0.15, 0.0]))

        elements['r5_label'] = Text("r = 5", font_size=28, color=self.COLORS['highlight'])
        elements['r5_label'].move_to(mid_r + np.array([0.3, -0.25, 0.0]))

        elements['formula'] = MathTex(
            r"S = \pi r^2",
            font_size=54,
            color=self.COLORS['highlight'],
        )
        elements['formula'].move_to(np.array([0.0, -3.0, 0.0]))

        elements['calc_step1'] = MathTex(
            r"S = \pi \times 5^2",
            font_size=44,
            color=self.COLORS['text'],
        )
        elements['calc_step1'].move_to(np.array([0.0, -3.3, 0.0]))

        elements['calc_result'] = MathTex(
            r"S = 25\pi",
            font_size=54,
            color=self.COLORS['highlight'],
        )
        elements['calc_result'].move_to(np.array([0.0, -3.3, 0.0]))

        elements['approx_value'] = MathTex(
            r"\approx 78.54",
            font_size=44,
            color=self.COLORS['text'],
        )
        elements['approx_value'].move_to(np.array([0.0, -4.0, 0.0]))

        elements['title_text'] = Text(
            "求圆的面积",
            font_size=52,
            color=self.COLORS['highlight'],
        )
        elements['title_text'].move_to(np.array([0.0, 3.2, 0.0]))

        elements['subtitle_text'] = Text(
            "半径 r = 5",
            font_size=36,
            color=self.COLORS['text'],
        )
        elements['subtitle_text'].move_to(np.array([0.0, 2.3, 0.0]))

        elements['final_title'] = Text(
            "圆的面积",
            font_size=48,
            color=self.COLORS['highlight'],
        )
        elements['final_title'].move_to(np.array([0.0, 3.0, 0.0]))

        elements['final_answer'] = MathTex(
            r"S = 25\pi \approx 78.54",
            font_size=48,
            color=self.COLORS['primary'],
        )
        elements['final_answer'].move_to(np.array([0.0, -3.0, 0.0]))

        return elements

    def play_scene_1(self, elements, geometry):
        expected = self.start_scene_with_audio(1)

        self.fade_in(elements['title_text'], run_time=1.0)
        self.wait_for_narration("求圆的面积")

        self.fade_in(elements['subtitle_text'], run_time=0.8)
        self.wait_for_narration("半径是5")

        subtitle = self.create_subtitle("已知半径 r = 5，求圆的面积")
        self.fade_in(subtitle, run_time=0.5)

        self.wait_until_scene_time(expected * 0.8)
        self.fade_out(subtitle, run_time=0.5)
        self.fade_out(elements['title_text'], run_time=0.5)
        self.fade_out(elements['subtitle_text'], run_time=0.5)

        self.end_scene_with_audio(expected)

    def play_scene_2(self, elements, geometry):
        expected = self.start_scene_with_audio(2)

        subtitle = self.create_subtitle("画一个圆，圆心为O")
        self.fade_in(subtitle, run_time=0.5)

        self.play(Create(elements['circle']), run_time=2.0)
        self.wait_for_narration("画一个圆")

        self.play(FadeIn(elements['center_dot']), run_time=0.5)
        self.wait_for_narration("圆心标记为O")

        self.fade_in(elements['center_label'], run_time=0.5)

        self.wait_until_scene_time(expected * 0.85)
        self.fade_out(subtitle, run_time=0.5)

        self.end_scene_with_audio(expected)

    def play_scene_3(self, elements, geometry):
        expected = self.start_scene_with_audio(3)

        subtitle = self.create_subtitle("标注半径 r = 5")
        self.fade_in(subtitle, run_time=0.5)

        self.play(Create(elements['radius_line']), run_time=1.2)
        self.wait_for_narration("标出半径")

        self.play(FadeIn(elements['radius_end_dot']), run_time=0.4)
        self.wait_for_narration("半径r等于5")

        self.fade_in(elements['radius_label'], run_time=0.4)
        self.fade_in(elements['r5_label'], run_time=0.4)
        self.highlight_element(elements['radius_line'], color=self.COLORS['highlight'], scale=1.1, duration=0.8)

        self.wait_until_scene_time(expected * 0.85)
        self.fade_out(subtitle, run_time=0.5)
        self.fade_out(elements['radius_label'], run_time=0.5)
        self.fade_out(elements['r5_label'], run_time=0.5)

        self.end_scene_with_audio(expected)

    def play_scene_4(self, elements, geometry):
        expected = self.start_scene_with_audio(4)

        subtitle = self.create_subtitle("圆的面积公式 S = πr²")
        self.fade_in(subtitle, run_time=0.5)

        self.wait_for_narration("面积公式")
        self.fade_in(elements['formula'], run_time=1.0)

        self.highlight_element(elements['formula'], color=self.COLORS['highlight'], scale=1.15, duration=1.0)
        self.wait_for_narration("S等于π乘以r的平方")

        self.wait_until_scene_time(expected * 0.85)
        self.fade_out(subtitle, run_time=0.5)

        self.end_scene_with_audio(expected)

    def play_scene_5(self, elements, geometry):
        expected = self.start_scene_with_audio(5)

        subtitle = self.create_subtitle("代入 r = 5 进行计算")
        self.fade_in(subtitle, run_time=0.5)

        self.fade_out(elements['formula'], run_time=0.5)
        self.wait_for_narration("把半径r等于5代入")

        self.fade_in(elements['calc_step1'], run_time=0.8)
        self.wait_for_narration("S等于π乘以5的平方")

        self.play(
            Transform(elements['calc_step1'], elements['calc_result']),
            run_time=1.2,
        )
        self.wait_for_narration("等于25π")

        self.highlight_element(elements['calc_result'], color=self.COLORS['highlight'], scale=1.2, duration=1.0)

        self.fade_in(elements['approx_value'], run_time=0.6)
        self.wait_until_scene_time(expected * 0.85)

        self.fade_out(subtitle, run_time=0.5)

        self.end_scene_with_audio(expected)

    def play_scene_6(self, elements, geometry):
        expected = self.start_scene_with_audio(6)

        self.play(
            FadeOut(elements['calc_result']),
            FadeOut(elements['approx_value']),
            run_time=0.6,
        )

        self.fade_in(elements['final_title'], run_time=0.8)
        self.wait_for_narration("圆的面积等于25π")

        self.fade_in(elements['final_answer'], run_time=1.0)

        self.play(
            elements['circle'].animate.set_stroke(width=6),
            run_time=0.8,
        )
        self.highlight_element(elements['circle'], color=self.COLORS['highlight'], scale=1.05, duration=1.0)

        self.wait_for_narration("约等于78.54")
        self.highlight_element(elements['final_answer'], color=self.COLORS['highlight'], scale=1.15, duration=0.8)

        self.wait_until_scene_time(expected * 0.9)

        subtitle = self.create_subtitle("圆的面积公式: S = πr²")
        self.fade_in(subtitle, run_time=0.5)
        self.wait_until_scene_time(expected * 0.97)

        self.end_scene_with_audio(expected)
