# Auto-generated by Claude Code Generation Mode
# Record ID: 40
# Generated at: 2026-07-05 01:58:13

from manim import *
import numpy as np
import sys
import os

# 添加项目根目录到路径
sys.path.insert(0, r"C:\Users\lxy\WorkBuddy\2026-06-30-16-26-23\education_agent")

# 设置音频目录环境变量（使用绝对路径）
os.environ["MATHANIM_AUDIO_DIR"] = r"C:\Users\lxy\WorkBuddy\2026-06-30-16-26-23\education_agent\output\audio\run_20260705_015801"
os.environ["MATHANIM_VIDEO_OUTPUT"] = r"C:\Users\lxy\WorkBuddy\2026-06-30-16-26-23\education_agent\output\videos"

# 导入基类
from animation.base_scene import MathAnimScene

# 设置渲染参数
config.pixel_width = 1920
config.pixel_height = 1080
config.frame_rate = 60

from manim import *
import numpy as np


class MathProblemScene(MathAnimScene):

    SCENES = [
        (1, '开场', 'audio_001_开场.mp3', None),
        (2, '画圆', 'audio_002_画圆.mp3', None),
        (3, '写出公式', 'audio_003_写出公式.mp3', None),
        (4, '代入数值', 'audio_004_代入数值.mp3', None),
        (5, '计算结果', 'audio_005_计算结果.mp3', None),
        (6, '总结', 'audio_006_总结.mp3', None),
    ]

    def calculate_geometry(self):
        math_radius = 5.0
        display_radius = 2.5

        center = np.array([0.0, 0.0, 0.0])

        right = center + np.array([display_radius, 0.0, 0.0])
        left = center + np.array([-display_radius, 0.0, 0.0])
        top = center + np.array([0.0, display_radius, 0.0])
        bottom = center + np.array([0.0, -display_radius, 0.0])

        radius_line_start = center.copy()
        radius_line_end = right.copy()

        area = math.pi * math_radius ** 2

        geometry = {
            'math_values': {
                'radius': math_radius,
                'area_exact': area,
                'area_pi_form': 25,
                'area_decimal': 25 * 3.14,
            },
            'display_values': {
                'radius': display_radius,
            },
            'center': center,
            'points': {
                'O': center,
                'A': right,
                'B': top,
                'C': left,
                'D': bottom,
            },
            'lines': {
                'radius_right': (radius_line_start, radius_line_end),
            },
            'circle': {
                'center': center,
                'radius': display_radius,
            },
        }
        return geometry

    def assert_geometry(self, geometry):
        assert abs(geometry['math_values']['radius'] - 5.0) < 1e-6, "Radius must be 5"
        assert abs(geometry['math_values']['area_pi_form'] - 25) < 1e-6, "Area coefficient must be 25"
        assert abs(geometry['math_values']['area_exact'] - 25 * math.pi) < 1e-6, "Area must be 25*pi"
        self._check_canvas_bounds(geometry)

    def define_elements(self, geometry):
        elements = {}
        elements['points'] = {}
        elements['labels'] = {}
        elements['lines'] = {}
        elements['shapes'] = {}
        elements['texts'] = {}

        center = geometry['center']
        display_radius = geometry['display_values']['radius']

        circle = Circle(
            radius=display_radius,
            color=self.COLORS['primary'],
            stroke_width=4,
        )
        circle.move_to(center)
        elements['shapes']['circle'] = circle

        center_dot = Dot(
            point=center,
            radius=0.06,
            color=self.COLORS['highlight'],
        )
        elements['points']['O'] = center_dot

        o_label = Text("O", font_size=28, color=self.COLORS['text'])
        o_label.next_to(center_dot, DOWN + LEFT, buff=0.1)
        elements['labels']['O'] = o_label

        right = geometry['points']['A']
        right_point = Dot(point=right, radius=0.05, color=self.COLORS['secondary'])
        elements['points']['A'] = right_point

        radius_line = Line(
            start=center,
            end=right,
            color=self.COLORS['secondary'],
            stroke_width=3,
        )
        elements['lines']['radius'] = radius_line

        return elements

    def play_scene_1(self, elements, geometry):
        expected = self.start_scene_with_audio(1)

        title = Text("求圆的面积", font_size=64, color=self.COLORS['highlight'])
        title.to_edge(UP, buff=1.0)

        subtitle = Text("已知半径 r = 5", font_size=40, color=self.COLORS['text'])
        subtitle.next_to(title, DOWN, buff=0.8)

        self.play(Write(title), run_time=1.5)

        self.wait_for_narration("求圆的面积")

        self.play(FadeIn(subtitle, shift=UP), run_time=1.0)
        self.wait(0.5)

        subtitle_group = VGroup(title, subtitle)
        self.play(FadeOut(subtitle_group), run_time=0.8)

        self.end_scene_with_audio(expected)

    def play_scene_2(self, elements, geometry):
        expected = self.start_scene_with_audio(2)

        circle = elements['shapes']['circle']
        center_dot = elements['points']['O']
        o_label = elements['labels']['O']
        radius_line = elements['lines']['radius']

        self.play(Create(circle), run_time=2.0)

        self.wait_for_narration("圆心标记为O")

        self.play(FadeIn(center_dot), Write(o_label), run_time=1.0)

        self.wait_for_narration("半径r等于5")

        self.play(Create(radius_line), run_time=1.2)

        r_label = MathTex(r"r = 5", font_size=36, color=self.COLORS['highlight'])
        r_label.next_to(radius_line, DOWN, buff=0.2)
        self.play(Write(r_label), run_time=1.0)
        self.wait(0.5)

        self.end_scene_with_audio(expected)

    def play_scene_3(self, elements, geometry):
        expected = self.start_scene_with_audio(3)

        circle = elements['shapes']['circle']
        center_dot = elements['points']['O']
        o_label = elements['labels']['O']
        radius_line = elements['lines']['radius']

        existing = VGroup(circle, center_dot, o_label, radius_line)
        self.play(existing.animate.shift(LEFT * 2.5).scale(0.7), run_time=1.2)

        self.wait_for_narration("圆的面积公式")

        formula_title = Text("面积公式", font_size=32, color=self.COLORS['text'])
        formula_title.move_to(np.array([3.5, 2.5, 0.0]))
        self.play(Write(formula_title), run_time=0.8)

        formula = MathTex(r"S = \pi r^{2}", font_size=56, color=self.COLORS['highlight'])
        formula.move_to(np.array([3.5, 1.0, 0.0]))
        self.play(Write(formula), run_time=1.5)

        self.wait_for_narration("S等于πr平方")

        self.play(self.highlight_element(formula))
        self.wait(0.8)

        self.end_scene_with_audio(expected)

    def play_scene_4(self, elements, geometry):
        expected = self.start_scene_with_audio(4)

        formula = MathTex(r"S = \pi r^{2}", font_size=56, color=self.COLORS['highlight'])
        formula.move_to(np.array([3.5, 1.0, 0.0]))

        self.wait_for_narration("将半径r等于5代入")

        step1 = MathTex(r"S = \pi \times 5^{2}", font_size=48, color=self.COLORS['text'])
        step1.move_to(np.array([3.5, -0.3, 0.0]))
        self.play(Write(step1), run_time=1.5)

        self.wait_for_narration("5的平方")

        self.highlight_element(formula)
        self.wait(0.5)

        self.end_scene_with_audio(expected)

    def play_scene_5(self, elements, geometry):
        expected = self.start_scene_with_audio(5)

        formula = MathTex(r"S = \pi r^{2}", font_size=56, color=self.COLORS['highlight'])
        formula.move_to(np.array([3.5, 1.0, 0.0]))
        step1 = MathTex(r"S = \pi \times 5^{2}", font_size=48, color=self.COLORS['text'])
        step1.move_to(np.array([3.5, -0.3, 0.0]))

        self.wait_for_narration("计算5的平方等于25")

        step2 = MathTex(r"S = 25\pi", font_size=56, color=self.COLORS['secondary'])
        step2.move_to(np.array([3.5, -1.5, 0.0]))
        self.play(Write(step2), run_time=1.5)

        self.highlight_element(step2)
        self.wait(0.5)

        self.wait_for_narration("78.5")

        step3 = MathTex(r"S \approx 78.5", font_size=44, color=self.COLORS['angle_a'])
        step3.move_to(np.array([3.5, -2.8, 0.0]))
        self.play(Write(step3), run_time=1.2)

        decimal_note = Text("(\\pi 取 3.14)", font_size=24, color=self.COLORS['text'])
        decimal_note.next_to(step3, DOWN, buff=0.2)
        self.play(FadeIn(decimal_note), run_time=0.8)

        self.wait(0.8)

        self.end_scene_with_audio(expected)

    def play_scene_6(self, elements, geometry):
        expected = self.start_scene_with_audio(6)

        circle = elements['shapes']['circle']
        center_dot = elements['points']['O']
        o_label = elements['labels']['O']
        radius_line = elements['lines']['radius']

        existing = VGroup(circle, center_dot, o_label, radius_line)
        self.play(existing.animate.move_to(np.array([-3.0, 0.0, 0.0])).scale(0.9), run_time=1.0)

        self.wait_for_narration("总结一下")

        summary_title = Text("解题总结", font_size=36, color=self.COLORS['highlight'])
        summary_title.move_to(np.array([2.5, 3.0, 0.0]))
        self.play(Write(summary_title), run_time=0.8)

        line1 = MathTex(r"S = \pi r^{2}", font_size=42, color=self.COLORS['text'])
        line1.move_to(np.array([2.5, 1.8, 0.0]))
        self.play(Write(line1), run_time=1.0)

        line2 = MathTex(r"r = 5", font_size=42, color=self.COLORS['text'])
        line2.move_to(np.array([2.5, 0.8, 0.0]))
        self.play(Write(line2), run_time=0.8)

        self.wait_for_narration("面积为25π")

        line3 = MathTex(r"S = 25\pi \approx 78.5", font_size=46, color=self.COLORS['secondary'])
        line3.move_to(np.array([2.5, -0.5, 0.0]))
        self.play(Write(line3), run_time=1.5)

        self.highlight_element(line3)

        box = SurroundingRectangle(line3, color=self.COLORS['highlight'], buff=0.15)
        self.play(Create(box), run_time=0.8)

        self.wait_for_narration("大家学会了吗")

        end_text = Text("谢谢观看！", font_size=44, color=self.COLORS['highlight'])
        end_text.to_edge(DOWN, buff=0.5)
        self.play(Write(end_text), run_time=1.0)
        self.wait(1.0)

        self.end_scene_with_audio(expected)
