# Auto-generated by Claude Code Generation Mode
# Record ID: 45
# Generated at: 2026-07-05 16:06:27

from manim import *
import numpy as np
import math
import sys
import os

# 添加项目根目录到路径
sys.path.insert(0, r"C:\Users\lxy\WorkBuddy\2026-06-30-16-26-23\education_agent")

# 设置音频目录环境变量（使用绝对路径）
os.environ["MATHANIM_AUDIO_DIR"] = r"C:\Users\lxy\WorkBuddy\2026-06-30-16-26-23\education_agent\output\audio\run_20260705_160609"
os.environ["MATHANIM_VIDEO_OUTPUT"] = r"C:\Users\lxy\WorkBuddy\2026-06-30-16-26-23\education_agent\output\videos"

# 导入基类
from animation.base_scene import MathAnimScene

# 设置渲染参数
config.pixel_width = 1920
config.pixel_height = 1080
config.frame_rate = 60

from manim import *
import numpy as np

class MathProblemScene(MathAnimScene):
    SCENES = [
        (1, "开场", "audio_001_开场.mp3", None),
        (2, "画圆", "audio_002_画圆.mp3", None),
        (3, "展示公式", "audio_003_展示公式.mp3", None),
        (4, "代入数值", "audio_004_代入数值.mp3", None),
        (5, "计算结果", "audio_005_计算结果.mp3", None),
        (6, "总结", "audio_006_总结.mp3", None),
    ]

    def calculate_geometry(self):
        import math
        geometry = {}
        # Mathematical values
        math_radius = 5
        math_area = math.pi * math_radius ** 2

        # Display radius - scaled for screen
        display_radius = 2.0

        # Center of circle (display coordinates)
        O = np.array([0.0, 0.0, 0.0])

        # Points on the circle (display coordinates)
        P_right = np.array([display_radius, 0.0, 0.0])
        P_top = np.array([0.0, display_radius, 0.0])
        P_left = np.array([-display_radius, 0.0, 0.0])
        P_bottom = np.array([0.0, -display_radius, 0.0])

        geometry['points'] = {
            'O': O,
            'P_right': P_right,
            'P_top': P_top,
            'P_left': P_left,
            'P_bottom': P_bottom,
        }

        geometry['lines'] = {
            'radius': {'start': O, 'end': P_right},
        }

        geometry['circles'] = {
            'main': {'center': O, 'radius': display_radius},
        }

        geometry['math'] = {
            'radius': math_radius,
            'area': math_area,
            'r_squared': math_radius ** 2,
        }

        geometry['display_radius'] = display_radius

        return geometry

    def assert_geometry(self, geometry):
        import math
        assert geometry['math']['radius'] == 5
        assert abs(geometry['math']['area'] - 25 * math.pi) < 1e-6
        assert geometry['display_radius'] == 2.0
        self._check_canvas_bounds(geometry)
        print("[OK] Geometry assertions passed")

    def define_elements(self, geometry):
        pts = geometry['points']
        elements = {'points': {}, 'lines': {}, 'circles': {}, 'labels': {}}

        # Create circle
        circle_cfg = geometry['circles']['main']
        circle = Circle(
            radius=circle_cfg['radius'],
            color=self.COLORS['primary'],
            stroke_width=3
        )
        circle.move_to(circle_cfg['center'])
        elements['circles']['main'] = circle

        # Create radius line
        radius_cfg = geometry['lines']['radius']
        radius_line = Line(
            start=radius_cfg['start'],
            end=radius_cfg['end'],
            color=self.COLORS['secondary'],
            stroke_width=4
        )
        elements['lines']['radius'] = radius_line

        # Create points
        elements['points']['O'] = Dot(pts['O'], color=self.COLORS['highlight'], radius=0.08)
        elements['points']['P_right'] = Dot(pts['P_right'], color=self.COLORS['highlight'], radius=0.08)

        # Create labels
        elements['labels']['O'] = Text("O", font_size=28, color=self.COLORS['highlight'])
        elements['labels']['O'].next_to(pts['O'], DOWN + LEFT, buff=0.15)

        elements['labels']['r'] = Text("r", font_size=32, color=self.COLORS['secondary'])
        elements['labels']['r'].next_to(geometry['lines']['radius']['start'] + (geometry['lines']['radius']['end'] - geometry['lines']['radius']['start']) * 0.5, UP, buff=0.15)

        return elements

    def play_scene_1(self, elements, geometry):
        expected = self.start_scene_with_audio(1)

        # Title
        title = Text("求圆的面积", font_size=60, color=self.COLORS['highlight'])
        title.to_edge(UP, buff=0.5)
        self.play(Write(title), run_time=1.2)

        self.wait_for_narration("今天我们来学习")

        # Subtitle
        subtitle = Text("已知圆的半径 r = 5", font_size=36, color=self.COLORS['text'])
        subtitle.next_to(title, DOWN, buff=0.8)
        self.play(FadeIn(subtitle), run_time=0.8)

        self.wait_for_narration("半径是五")

        self.end_scene_with_audio(expected)

    def play_scene_2(self, elements, geometry):
        expected = self.start_scene_with_audio(2)

        # Clear previous
        self.clear()

        # Subtitle for this scene
        sub = self.create_subtitle("画一个圆，标出半径")
        self.play(FadeIn(sub), run_time=0.4)

        # Draw circle
        circle = elements['circles']['main']
        self.play(Create(circle), run_time=1.5)

        self.wait_for_narration("画一个圆")

        # Show center O
        center_dot = elements['points']['O']
        center_label = elements['labels']['O']
        self.play(FadeIn(center_dot), Write(center_label), run_time=0.8)

        self.wait_for_narration("标出圆心O")

        # Draw radius
        radius_line = elements['lines']['radius']
        r_label = elements['labels']['r']
        self.play(Create(radius_line), run_time=1.0)

        self.wait_for_narration("画一条半径")

        # Add radius value label
        r_value = MathTex(r"r = 5", font_size=36, color=self.COLORS['secondary'])
        r_value.next_to(radius_line, UP, buff=0.3)
        self.play(Write(r_value), run_time=0.8)

        self.wait_for_narration("长度为五")

        self.end_scene_with_audio(expected)

    def play_scene_3(self, elements, geometry):
        expected = self.start_scene_with_audio(3)

        # Clear previous
        self.clear()

        # Subtitle
        sub = self.create_subtitle("圆的面积公式")
        self.play(FadeIn(sub), run_time=0.4)

        # Show the formula
        formula_title = Text("圆的面积公式", font_size=44, color=self.COLORS['highlight'])
        formula_title.to_edge(UP, buff=0.5)
        self.play(Write(formula_title), run_time=0.8)

        self.wait_for_narration("圆的面积公式")

        # Main formula S = pi * r^2
        formula = MathTex(r"S = \pi r^{2}", font_size=64, color=self.COLORS['primary'])
        formula.move_to([0, 0.5, 0])
        self.play(Write(formula), run_time=1.2)

        self.wait_for_narration("S等于π乘以r的平方")

        # Explanation
        explanation = Text("即 半径的平方 × 圆周率 π", font_size=32, color=self.COLORS['text'])
        explanation.next_to(formula, DOWN, buff=0.8)
        self.play(FadeIn(explanation), run_time=0.8)

        self.wait_for_narration("半径的平方乘以圆周率")

        self.end_scene_with_audio(expected)

    def play_scene_4(self, elements, geometry):
        expected = self.start_scene_with_audio(4)

        # Clear previous
        self.clear()

        # Subtitle
        sub = self.create_subtitle("代入 r = 5")
        self.play(FadeIn(sub), run_time=0.4)

        # Show substitution step
        step_title = Text("代入数值", font_size=44, color=self.COLORS['highlight'])
        step_title.to_edge(UP, buff=0.5)
        self.play(Write(step_title), run_time=0.8)

        self.wait_for_narration("代入数值")

        # Formula with substitution
        formula_sub = MathTex(r"S = \pi \times 5^{2}", font_size=56, color=self.COLORS['primary'])
        formula_sub.move_to([0, 1.0, 0])
        self.play(Write(formula_sub), run_time=1.2)

        self.wait_for_narration("把半径r等于五代入公式")

        # Show r = 5 highlighted
        highlight_box = SurroundingRectangle(formula_sub[0][4:6], color=self.COLORS['secondary'], buff=0.1)
        self.play(Create(highlight_box), run_time=0.6)

        self.wait_for_narration("得到S等于π乘以五的平方")

        self.end_scene_with_audio(expected)

    def play_scene_5(self, elements, geometry):
        expected = self.start_scene_with_audio(5)

        # Clear previous
        self.clear()

        # Subtitle
        sub = self.create_subtitle("计算过程")
        self.play(FadeIn(sub), run_time=0.4)

        # Title
        step_title = Text("计算结果", font_size=44, color=self.COLORS['highlight'])
        step_title.to_edge(UP, buff=0.5)
        self.play(Write(step_title), run_time=0.8)

        self.wait_for_narration("计算结果")

        # Step 1: 5 squared = 25
        step1 = MathTex(r"5^{2} = 25", font_size=48, color=self.COLORS['text'])
        step1.move_to([0, 1.5, 0])
        self.play(Write(step1), run_time=1.0)

        self.wait_for_narration("五的平方等于二十五")

        # Anthropic: S = 25 pi
        step2 = MathTex(r"S = 25\pi", font_size=56, color=self.COLORS['primary'])
        step2.move_to([0, 0.2, 0])
        self.play(Write(step2), run_time=1.0)

        self.wait_for_narration("所以圆的面积S等于二十五π")

        # Highlight the result
        self.highlight_element(step2, color=self.COLORS['highlight'], scale=1.2, duration=0.6)

        # Step 3: approximate value
        step3 = MathTex(r"S \approx 78.54", font_size=44, color=self.COLORS['text'])
        step3.move_to([0, -1.2, 0])
        self.play(FadeIn(step3), run_time=0.8)

        self.wait_for_narration("约等于78.54")

        self.end_scene_with_audio(expected)

    def play_scene_6(self, elements, geometry):
        expected = self.start_scene_with_audio(6)

        # Clear previous
        self.clear()

        # Subtitle
        sub = self.create_subtitle("总结")
        self.play(FadeIn(sub), run_time=0.4)

        # Title
        title = Text("总结", font_size=56, color=self.COLORS['highlight'])
        title.to_edge(UP, buff=0.5)
        self.play(Write(title), run_time=0.8)

        self.wait_for_narration("总结一下")

        # Summary formula
        summary = MathTex(r"S = \pi r^{2} = 25\pi \approx 78.54", font_size=48, color=self.COLORS['primary'])
        summary.move_to([0, 0.5, 0])
        self.play(Write(summary), run_time=1.5)

        self.wait_for_narration("半径为五的圆")

        # Final answer box
        answer_box = SurroundingRectangle(summary, color=self.COLORS['highlight'], buff=0.2)
        self.play(Create(answer_box), run_time=0.8)

        self.wait_for_narration("面积等于二十五π")

        # Final message
        final_msg = Text("圆的面积 = 25π ≈ 78.54", font_size=36, color=self.COLORS['text'])
        final_msg.move_to([0, -1.5, 0])
        self.play(FadeIn(final_msg), run_time=0.8)

        self.wait_for_narration("大家学会了吗")

        self.end_scene_with_audio(expected)
