# Auto-generated by Claude Code Generation Mode
# Record ID: 39
# Generated at: 2026-07-05 01:49:18

from manim import *
import numpy as np
import sys
import os

# 添加项目根目录到路径
sys.path.insert(0, r"C:\Users\lxy\WorkBuddy\2026-06-30-16-26-23\education_agent")

# 设置音频目录环境变量（使用绝对路径）
os.environ["MATHANIM_AUDIO_DIR"] = r"C:\Users\lxy\WorkBuddy\2026-06-30-16-26-23\education_agent\output\audio\run_20260705_014906"
os.environ["MATHANIM_VIDEO_OUTPUT"] = r"C:\Users\lxy\WorkBuddy\2026-06-30-16-26-23\education_agent\output\videos"

# 导入基类
from animation.base_scene import MathAnimScene

# 设置渲染参数
config.pixel_width = 1920
config.pixel_height = 1080
config.frame_rate = 60

from manim import *
import numpy as np

class MathProblemScene(MathAnimScene):
    
    SCENES = [
        (1, "开场", "audio_001_开场.mp3", None),
        (2, "画圆", "audio_002_画圆.mp3", None),
        (3, "写出公式", "audio_003_写出公式.mp3", None),
        (4, "代入半径", "audio_004_代入半径.mp3", None),
        (5, "计算结果", "audio_005_计算结果.mp3", None),
        (6, "总结", "audio_006_总结.mp3", None),
    ]
    
    def calculate_geometry(self):
        # 圆的数学参数
        radius = 5  # 数学半径
        display_radius = 2.0  # 显示半径（用于屏幕绘制）
        
        geometry = {
            'radius': radius,
            'display_radius': display_radius,
            'area': np.pi * radius ** 2,  # 数学面积值
            'area_value': 25 * np.pi,  # 25π
            'approx_area': 78.54,  # 近似值
            'points': {
                'O': np.array([0.0, 0.0, 0.0]),  # 圆心
            },
            'circles': {
                'main_circle': {
                    'center': np.array([0.0, 0.0, 0.0]),
                    'radius': display_radius,
                }
            },
            'lines': {
                'radius_line': {
                    'start': np.array([0.0, 0.0, 0.0]),
                    'end': np.array([display_radius, 0.0, 0.0]),
                }
            },
            'labels': {
                'O_pos': np.array([0.0, 0.0, 0.0]),
                'r_pos': np.array([display_radius / 2, -0.35, 0.0]),
            }
        }
        
        return geometry
    
    def assert_geometry(self, geometry):
        # 验证半径正确
        assert geometry['radius'] == 5, f"Expected radius 5, got {geometry['radius']}"
        
        # 验证面积计算正确
        expected_area = np.pi * 5 ** 2
        assert abs(geometry['area'] - expected_area) < 1e-6, "Area calculation incorrect"
        
        # 验证25π
        assert abs(geometry['area_value'] - 25 * np.pi) < 1e-6, "25π calculation incorrect"
        
        # 验证显示半径在画布范围内
        assert geometry['display_radius'] <= 3.0, "Display radius too large"
        
        # 检查画布范围
        self._check_canvas_bounds(geometry)
    
    def define_elements(self, geometry):
        elements = {
            'points': {},
            'circles': {},
            'lines': {},
            'labels': {},
            'formulas': {},
        }
        
        # 圆心O
        center = geometry['points']['O']
        elements['points']['O'] = Dot(
            point=center,
            radius=0.08,
            color=self.COLORS['highlight']
        )
        
        # 主圆
        elements['circles']['main_circle'] = Circle(
            radius=geometry['display_radius'],
            color=self.COLORS['primary'],
            stroke_width=4,
        )
        elements['circles']['main_circle'].move_to(center)
        
        # 半径线
        line_info = geometry['lines']['radius_line']
        elements['lines']['radius_line'] = Line(
            start=line_info['start'],
            end=line_info['end'],
            color=self.COLORS['secondary'],
            stroke_width=3,
        )
        
        # 标签
        elements['labels']['O'] = Text(
            "O",
            font_size=36,
            color=self.COLORS['highlight']
        )
        elements['labels']['O'].next_to(center, DOWN + LEFT, buff=0.15)
        
        elements['labels']['r5'] = Text(
            "r = 5",
            font_size=32,
            color=self.COLORS['secondary']
        )
        elements['labels']['r5'].move_to(geometry['labels']['r_pos'])
        
        # 公式元素
        elements['formulas']['title'] = Text(
            "求圆的面积",
            font_size=54,
            color=self.COLORS['highlight']
        )
        elements['formulas']['title'].to_edge(UP, buff=0.5)
        
        elements['formulas']['given'] = Text(
            "已知半径 r = 5",
            font_size=34,
            color=self.COLORS['text']
        )
        elements['formulas']['given'].next_to(elements['formulas']['title'], DOWN, buff=0.4)
        
        # 面积公式
        elements['formulas']['formula'] = MathTex(
            r"S = \pi r^{2}",
            font_size=48,
            color=self.COLORS['primary']
        )
        
        # 代入
        elements['formulas']['substitute'] = MathTex(
            r"S = \pi \times 5^{2}",
            font_size=48,
            color=self.COLORS['primary']
        )
        
        # 计算
        elements['formulas']['compute'] = MathTex(
            r"S = 25\pi",
            font_size=52,
            color=self.COLORS['highlight']
        )
        
        # 近似值
        elements['formulas']['approx'] = MathTex(
            r"S \approx 78.54",
            font_size=42,
            color=self.COLORS['text']
        )
        
        # 总结公式
        elements['formulas']['summary'] = MathTex(
            r"S = \pi r^{2} = 25\pi",
            font_size=46,
            color=self.COLORS['highlight']
        )
        
        return elements
    
    def play_scene_1(self, elements, geometry):
        expected = self.start_scene_with_audio(1)
        
        # 显示标题
        self.play(Write(elements['formulas']['title']), run_time=1.2)
        self.wait_for_narration("求圆的面积")
        
        # 显示已知条件
        self.play(FadeIn(elements['formulas']['given'], shift=UP * 0.3), run_time=1.0)
        self.wait_for_narration("半径是五")
        
        # 创建副标题
        subtitle = self.create_subtitle("已知圆的半径 r = 5，求面积")
        self.play(FadeIn(subtitle), run_time=0.5)
        
        self.end_scene_with_audio(expected)
    
    def play_scene_2(self, elements, geometry):
        expected = self.start_scene_with_audio(2)
        
        subtitle = self.create_subtitle("绘制圆和半径")
        self.play(FadeIn(subtitle), run_time=0.4)
        
        # 移除上方的标题和条件（它们不再需要显示）
        if hasattr(self, '_old_title_group'):
            self.play(FadeOut(self._old_title_group), run_time=0.5)
        
        # 移除标题区域
        self.play(
            FadeOut(elements['formulas']['title']),
            FadeOut(elements['formulas']['given']),
            run_time=0.6
        )
        
        # 绘制圆
        self.wait_for_narration("画一个圆")
        self.play(Create(elements['circles']['main_circle']), run_time=2.0)
        
        # 添加圆心
        self.play(FadeIn(elements['points']['O']), run_time=0.5)
        self.play(Write(elements['labels']['O']), run_time=0.6)
        
        # 绘制半径
        self.wait_for_narration("半径五")
        self.play(Create(elements['lines']['radius_line']), run_time=1.0)
        self.play(Write(elements['labels']['r5']), run_time=0.6)
        
        # 高亮半径
        self.highlight_element(elements['lines']['radius_line'], color=self.COLORS['highlight'])
        
        self.end_scene_with_audio(expected)
    
    def play_scene_3(self, elements, geometry):
        expected = self.start_scene_with_audio(3)
        
        subtitle = self.create_subtitle("写出面积公式")
        self.play(FadeIn(subtitle), run_time=0.4)
        
        # 显示公式
        self.wait_for_narration("面积公式")
        formula = elements['formulas']['formula']
        formula.to_edge(DOWN, buff=1.5)
        self.play(Write(formula), run_time=1.5)
        
        # 高亮r和π
        self.wait_for_narration("r是圆的半径")
        self.highlight_element(formula, color=self.COLORS['highlight'], scale=1.1)
        
        self.end_scene_with_audio(expected)
    
    def play_scene_4(self, elements, geometry):
        expected = self.start_scene_with_audio(4)
        
        subtitle = self.create_subtitle("代入半径 r = 5")
        self.play(FadeIn(subtitle), run_time=0.4)
        
        # 替换为代入公式
        old_formula = elements['formulas']['formula']
        new_formula = elements['formulas']['substitute']
        new_formula.move_to(old_formula.get_center())
        
        self.wait_for_narration("代入公式")
        self.play(
            Transform(old_formula, new_formula),
            run_time=1.5
        )
        
        # 高亮5
        self.wait_for_narration("二十五π")
        
        self.end_scene_with_audio(expected)
    
    def play_scene_5(self, elements, geometry):
        expected = self.start_scene_with_audio(5)
        
        subtitle = self.create_subtitle("计算最终结果")
        self.play(FadeIn(subtitle), run_time=0.4)
        
        # 变换为最终结果
        current = elements['formulas']['substitute']
        result = elements['formulas']['compute']
        result.move_to(current.get_center())
        
        self.wait_for_narration("二十五π")
        self.play(
            Transform(current, result),
            run_time=1.5
        )
        
        # 高亮结果
        self.play(
            elements['formulas']['compute'].animate.set_color(self.COLORS['highlight']),
            run_time=0.5
        )
        
        # 显示近似值
        approx = elements['formulas']['approx']
        approx.next_to(elements['formulas']['compute'], DOWN, buff=0.5)
        
        self.wait_for_narration("七十八点五四")
        self.play(Write(approx), run_time=1.0)
        
        self.end_scene_with_audio(expected)
    
    def play_scene_6(self, elements, geometry):
        expected = self.start_scene_with_audio(6)
        
        subtitle = self.create_subtitle("知识点总结")
        self.play(FadeIn(subtitle), run_time=0.4)
        
        # 创建总结框
        summary_box = SurroundingRectangle(
            elements['circles']['main_circle'],
            color=self.COLORS['highlight'],
            buff=0.3,
            stroke_width=2,
        )
        self.play(Create(summary_box), run_time=0.8)
        
        # 移到顶部显示总结公式
        summary_formula = elements['formulas']['summary']
        summary_formula.to_edge(UP, buff=0.5)
        
        self.wait_for_narration("面积公式")
        self.play(Write(summary_formula), run_time=1.5)
        
        # 高亮所有关键元素
        self.wait_for_narration("二十五π")
        self.highlight_element(elements['circles']['main_circle'], color=self.COLORS['highlight'])
        self.highlight_element(elements['lines']['radius_line'], color=self.COLORS['highlight'])
        self.highlight_element(elements['formulas']['compute'], color=self.COLORS['highlight'])
        
        # 最终闪烁效果
        self.play(
            elements['formulas']['compute'].animate.scale(1.3),
            run_time=0.6
        )
        self.play(
            elements['formulas']['compute'].animate.scale(1 / 1.3),
            run_time=0.6
        )
        
        self.end_scene_with_audio(expected)
