# Auto-generated by Claude Code Generation Mode
# Record ID: 49
# Generated at: 2026-07-05 17:06:09

from manim import *
import numpy as np
import math
import sys
import os

# 添加项目根目录到路径
sys.path.insert(0, r"C:\Users\lxy\WorkBuddy\2026-06-30-16-26-23\education_agent")

# 设置音频目录环境变量（使用绝对路径）
os.environ["MATHANIM_AUDIO_DIR"] = r"C:\Users\lxy\WorkBuddy\2026-06-30-16-26-23\education_agent\output\audio\run_20260705_170600"
os.environ["MATHANIM_VIDEO_OUTPUT"] = r"C:\Users\lxy\WorkBuddy\2026-06-30-16-26-23\education_agent\output\videos"

# 导入基类
from animation.base_scene import MathAnimScene

# 设置渲染参数
config.pixel_width = 1920
config.pixel_height = 1080
config.frame_rate = 60

from manim import *
import numpy as np

class MathProblemScene(MathAnimScene):
    SCENES = [
        (1, "开场", "audio_001_开场.mp3", None),
        (2, "画三角形", "audio_002_画三角形.mp3", None),
        (3, "标注边长", "audio_003_标注边长.mp3", None),
        (4, "写出公式", "audio_004_写出公式.mp3", None),
        (5, "代入计算", "audio_005_代入计算.mp3", None),
        (6, "总结", "audio_006_总结.mp3", None),
    ]

    def calculate_geometry(self):
        # Mathematical values: AC=3, CB=4, AB=5
        # Display scaling factor to fit canvas
        scale = 0.6

        # Display coordinates: place C at origin, A up, B right
        A_disp = np.array([0.0, 3.0 * scale, 0.0])        # C at origin, A above
        B_disp = np.array([4.0 * scale, 0.0, 0.0])        # B to the right
        C_disp = np.array([0.0, 0.0, 0.0])                # C at origin (right angle)

        # Recompute with cleaner scale for readability
        # Use scale 0.8 so triangle is nicely sized
        s = 0.8
        A_disp = np.array([0.0, 3.0 * s, 0.0])
        B_disp = np.array([4.0 * s, 0.0, 0.0])
        C_disp = np.array([0.0, 0.0, 0.0])

        # Verify AB length in display coordinates
        AB_display_length = np.linalg.norm(B_disp - A_disp)

        # Midpoints for label placement
        mid_AC = (A_disp + C_disp) / 2.0
        mid_CB = (C_disp + B_disp) / 2.0
        mid_AB = (A_disp + B_disp) / 2.0

        geometry = {
            'points': {
                'A': A_disp,
                'B': B_disp,
                'C': C_disp,
            },
            'lines': {
                'AC': {'start': A_disp, 'end': C_disp, 'length': 3.0},
                'CB': {'start': C_disp, 'end': B_disp, 'length': 4.0},
                'AB': {'start': A_disp, 'end': B_disp, 'length': 5.0},
                'AC_label_pos': {'start': mid_AC, 'end': mid_AC + np.array([-0.5, 0, 0])},
                'CB_label_pos': {'start': mid_CB, 'end': mid_CB + np.array([0, -0.5, 0])},
                'AB_label_pos': {'start': mid_AB, 'end': mid_AB + np.array([0.3, 0.3, 0])},
            },
            'circles': {},
            'angles': {
                'C': {'value': np.pi / 2, 'deg': 90.0},
            },
            'midpoints': {
                'AC': mid_AC,
                'CB': mid_CB,
                'AB': mid_AB,
            },
            'math': {
                'AC': 3.0,
                'CB': 4.0,
                'AB': 5.0,
                'AB_squared': 25.0,
                'AC_squared': 9.0,
                'CB_squared': 16.0,
            },
        }
        return geometry

    def assert_geometry(self, geometry):
        pts = geometry['points']
        A, B, C = pts['A'], pts['B'], pts['C']

        # Verify right angle at C: vectors CA and CB should be perpendicular
        CA = A - C
        CB = B - C
        dot_product = np.dot(CA, CB)
        assert abs(dot_product) < 1e-6, f"Angle C is not 90 degrees, dot product = {dot_product}"

        # Verify side lengths (display coordinates scaled by 0.8)
        AC_len = np.linalg.norm(A - C)
        CB_len = np.linalg.norm(C - B)
        AB_len = np.linalg.norm(A - B)

        assert abs(AC_len - 2.4) < 1e-6, f"AC display length should be 2.4, got {AC_len}"
        assert abs(CB_len - 3.2) < 1e-6, f"CB display length should be 3.2, got {CB_len}"
        # AB should be 5 * 0.8 = 4.0
        assert abs(AB_len - 4.0) < 1e-6, f"AB display length should be 4.0, got {AB_len}"

        # Verify Pythagorean theorem holds in math values
        math = geometry['math']
        assert abs(math['AC_squared'] + math['CB_squared'] - math['AB_squared']) < 1e-6

        self._check_canvas_bounds(geometry)

    def define_elements(self, geometry):
        pts = geometry['points']
        elements = {
            'points': {},
            'lines': {},
            'labels': {},
            'angles': {},
            'misc': {},
        }

        # Create points (dots)
        for name, coord in pts.items():
            dot = Dot(coord, color=self.COLORS['highlight'], radius=0.08)
            elements['points'][name] = dot

        # Create point labels (A, B, C)
        label_offsets = {
            'A': np.array([-0.4, 0.2, 0]),
            'B': np.array([0.4, -0.2, 0]),
            'C': np.array([-0.4, -0.4, 0]),
        }
        for name, coord in pts.items():
            label = Text(name, font_size=36, color=self.COLORS['text'])
            label.move_to(coord + label_offsets[name])
            elements['labels'][name] = label

        # Create triangle lines
        elements['lines']['AC'] = Line(
            start=geometry['lines']['AC']['start'],
            end=geometry['lines']['AC']['end'],
            color=self.COLORS['primary'],
            stroke_width=4,
        )
        elements['lines']['CB'] = Line(
            start=geometry['lines']['CB']['start'],
            end=geometry['lines']['CB']['end'],
            color=self.COLORS['primary'],
            stroke_width=4,
        )
        elements['lines']['AB'] = Line(
            start=geometry['lines']['AB']['start'],
            end=geometry['lines']['AB']['end'],
            color=self.COLORS['secondary'],
            stroke_width=4,
        )

        # Right angle marker at C (small square)
        right_angle_size = 0.3
        C = pts['C']
        # Direction vectors from C
        dir_to_A = (pts['A'] - C) / np.linalg.norm(pts['A'] - C)
        dir_to_B = (pts['B'] - C) / np.linalg.norm(pts['B'] - C)
        p1 = C + dir_to_A * right_angle_size
        p2 = C + dir_to_A * right_angle_size + dir_to_B * right_angle_size
        p3 = C + dir_to_B * right_angle_size
        right_angle = Polygon(p1, p2, p3, color=self.COLORS['highlight'], stroke_width=2)
        elements['angles']['C'] = right_angle

        return elements

    def play_scene_1(self, elements, geometry):
        expected = self.start_scene_with_audio(1)

        # Subtitle for this scene
        sub = self.create_subtitle("勾股定理应用")
        self.play(FadeIn(sub), run_time=0.5)

        # Show title
        title = Text("勾股定理的应用", font_size=54, color=self.COLORS['highlight'])
        title.move_to(np.array([0, 1.5, 0]))
        self.play(Write(title), run_time=1.2)
        self.wait_for_narration("勾股定理")

        # Show problem statement
        problem = Text("直角三角形ABC中，角C等于90度", font_size=28, color=self.COLORS['text'])
        problem.move_to(np.array([0, 0.2, 0]))
        self.play(Write(problem), run_time=1.2)

        problem2 = Text("AC等于3，CB等于4，求AB", font_size=28, color=self.COLORS['text'])
        problem2.move_to(np.array([0, -0.5, 0]))
        self.play(Write(problem2), run_time=1.0)

        self.wait(1.0)
        self.play(FadeOut(title), FadeOut(problem), FadeOut(problem2), FadeOut(sub), run_time=0.8)
        self.end_scene_with_audio(expected)

    def play_scene_2(self, elements, geometry):
        expected = self.start_scene_with_audio(2)

        # Subtitle
        sub = self.create_subtitle("画直角三角形")
        self.play(FadeIn(sub), run_time=0.5)

        # Draw triangle step by step
        # First the right-angle sides
        self.play(Create(elements['lines']['AC']), run_time=1.0)
        self.play(Create(elements['lines']['CB']), run_time=1.0)

        # Then the hypotenuse
        self.play(Create(elements['lines']['AB']), run_time=1.2)

        # Show the right angle marker
        self.play(Create(elements['angles']['C']), run_time=0.6)

        # Add vertex dots and labels
        self.play(
            FadeIn(elements['points']['A']),
            FadeIn(elements['points']['B']),
            FadeIn(elements['points']['C']),
            run_time=0.6,
        )
        self.play(
            FadeIn(elements['labels']['A']),
            FadeIn(elements['labels']['B']),
            FadeIn(elements['labels']['C']),
            run_time=0.6,
        )

        self.wait_for_narration("直角三角形")
        self.wait(0.8)
        self.play(FadeOut(sub), run_time=0.5)
        self.end_scene_with_audio(expected)

    def play_scene_3(self, elements, geometry):
        expected = self.start_scene_with_audio(3)

        # Subtitle
        sub = self.create_subtitle("标注已知边长")
        self.play(FadeIn(sub), run_time=0.5)

        # Label AC = 3
        ac_label = MathTex(r"AC = 3", font_size=36, color=self.COLORS['primary'])
        ac_label.move_to(geometry['midpoints']['AC'] + np.array([-0.7, 0, 0]))
        self.play(Write(ac_label), run_time=1.0)
        self.wait_for_narration("AC等于3")

        # Label CB = 4
        cb_label = MathTex(r"CB = 4", font_size=36, color=self.COLORS['primary'])
        cb_label.move_to(geometry['midpoints']['CB'] + np.array([0, -0.6, 0]))
        self.play(Write(cb_label), run_time=1.0)
        self.wait_for_narration("CB等于4")

        # Highlight AC and CB to emphasize known sides
        self.highlight_element(elements['lines']['AC'], color=self.COLORS['highlight'], scale=1.0)
        self.highlight_element(elements['lines']['CB'], color=self.COLORS['highlight'], scale=1.0)

        # Question for AB
        ab_q = MathTex(r"AB = ?", font_size=40, color=self.COLORS['secondary'])
        ab_q.move_to(geometry['midpoints']['AB'] + np.array([0.5, 0.4, 0]))
        self.play(Write(ab_q), run_time=1.0)
        self.wait_for_narration("斜边AB")

        self.wait(0.5)
        self.play(FadeOut(sub), run_time=0.5)
        self.end_scene_with_audio(expected)

    def play_scene_4(self, elements, geometry):
        expected = self.start_scene_with_audio(4)

        # Subtitle
        sub = self.create_subtitle("勾股定理公式")
        self.play(FadeIn(sub), run_time=0.5)

        # Display Pythagorean theorem formula
        formula1 = MathTex(r"AB^2 = AC^2 + CB^2", font_size=44, color=self.COLORS['highlight'])
        formula1.move_to(np.array([0, 3.0, 0]))
        self.play(Write(formula1), run_time=1.5)
        self.wait_for_narration("勾股定理")
        self.wait_for_narration("AB的平方")

        # Brief explanation
        note = Text("斜边平方 = 两直角边平方之和", font_size=24, color=self.COLORS['text'])
        note.move_to(np.array([0, 2.3, 0]))
        self.play(FadeIn(note), run_time=1.0)

        self.wait(1.0)
        self.play(FadeOut(formula1), FadeOut(note), FadeOut(sub), run_time=0.8)
        self.end_scene_with_audio(expected)

    def play_scene_5(self, elements, geometry):
        expected = self.start_scene_with_audio(5)

        # Subtitle
        sub = self.create_subtitle("代入数值计算")
        self.play(FadeIn(sub), run_time=0.5)

        # Show substitution step by step
        step1 = MathTex(r"AB^2 = 3^2 + 4^2", font_size=42, color=self.COLORS['text'])
        step1.move_to(np.array([0, 3.0, 0]))
        self.play(Write(step1), run_time=1.2)
        self.wait_for_narration("代入数值")

        # Show calculation
        step2 = MathTex(r"AB^2 = 9 + 16", font_size=42, color=self.COLORS['text'])
        step2.move_to(np.array([0, 2.2, 0]))
        self.play(Transform(step1, step2), run_time=1.0)
        self.wait_for_narration("9加16")

        step3 = MathTex(r"AB^2 = 25", font_size=44, color=self.COLORS['primary'])
        step3.move_to(np.array([0, 1.4, 0]))
        self.play(Write(step3), run_time=1.0)

        # Final answer
        step4 = MathTex(r"AB = 5", font_size=52, color=self.COLORS['highlight'])
        step4.move_to(np.array([0, 0.4, 0]))
        self.play(Write(step4), run_time=1.2)
        self.wait_for_narration("AB等于5")

        # Highlight the answer
        box = SurroundingRectangle(step4, color=self.COLORS['highlight'], buff=0.15)
        self.play(Create(box), run_time=0.8)

        self.wait(0.5)
        self.play(FadeOut(step1), FadeOut(step3), FadeOut(step4), FadeOut(box), FadeOut(sub), run_time=0.8)
        self.end_scene_with_audio(expected)

    def play_scene_6(self, elements, geometry):
        expected = self.start_scene_with_audio(6)

        # Subtitle
        sub = self.create_subtitle("结论：AB=5")
        self.play(FadeIn(sub), run_time=0.5)

        # Highlight all sides
        self.highlight_element(elements['lines']['AC'], color=self.COLORS['highlight'], scale=1.0)
        self.highlight_element(elements['lines']['CB'], color=self.COLORS['highlight'], scale=1.0)
        self.highlight_element(elements['lines']['AB'], color=self.COLORS['highlight'], scale=1.0)

        # Final summary
        summary1 = Text("勾三股四弦五", font_size=54, color=self.COLORS['highlight'])
        summary1.move_to(np.array([0, 2.8, 0]))
        self.play(Write(summary1), run_time=1.5)
        self.wait_for_narration("勾三股四弦五")

        summary2 = MathTex(r"AB = 5", font_size=56, color=self.COLORS['primary'])
        summary2.move_to(np.array([0, 1.5, 0]))
        self.play(Write(summary2), run_time=1.2)

        box = SurroundingRectangle(summary2, color=self.COLORS['highlight'], buff=0.2)
        self.play(Create(box), run_time=0.8)

        self.wait_for_narration("AB的长度是5")
        self.wait(1.0)
        self.play(FadeOut(sub), run_time=0.5)
        self.end_scene_with_audio(expected)
