# Auto-generated by Claude Code Generation Mode
# Record ID: 47
# Generated at: 2026-07-05 16:25:34

from manim import *
import numpy as np
import math
import sys
import os

# 添加项目根目录到路径
sys.path.insert(0, r"C:\Users\lxy\WorkBuddy\2026-06-30-16-26-23\education_agent")

# 设置音频目录环境变量（使用绝对路径）
os.environ["MATHANIM_AUDIO_DIR"] = r"C:\Users\lxy\WorkBuddy\2026-06-30-16-26-23\education_agent\output\audio\run_20260705_162521"
os.environ["MATHANIM_VIDEO_OUTPUT"] = r"C:\Users\lxy\WorkBuddy\2026-06-30-16-26-23\education_agent\output\videos"

# 导入基类
from animation.base_scene import MathAnimScene

# 设置渲染参数
config.pixel_width = 1920
config.pixel_height = 1080
config.frame_rate = 60

from manim import *
import numpy as np
import math


class MathProblemScene(MathAnimScene):
    SCENES = [
        (1, "开场", "audio_001_开场.mp3", None),
        (2, "画三角形", "audio_002_画三角形.mp3", None),
        (3, "标注边长", "audio_003_标注边长.mp3", None),
        (4, "应用勾股定理", "audio_004_应用勾股定理.mp3", None),
        (5, "代入计算", "audio_005_代入计算.mp3", None),
        (6, "总结", "audio_006_总结.mp3", None),
    ]

    def calculate_geometry(self):
        # 题目的数学值
        AC = 3.0  # 直角边
        CB = 4.0  # 直角边
        AB = math.sqrt(AC ** 2 + CB ** 2)  # 斜边 = 5

        # 显示坐标缩放因子：让图形适应画布
        # 斜边 AB = 5, 我们希望它在屏幕上显示约 5 个单位
        scale = 0.8
        AC_display = AC * scale  # 2.4
        CB_display = CB * scale  # 3.2

        # 直角在 C 点, 放置在画布中下方
        C = np.array([0.0, -2.0, 0.0])
        # A 在 C 上方 (AC 竖直向上), 修正: A 在右上方更适合显示斜边
        # 我们让 C 为原点, AC 沿 x 轴正方向, CB 沿 y 轴正方向
        # 这样 AB 是从 (AC,0) 到 (0,CB) 的连线
        C = np.array([0.0, 0.0, 0.0])
        A = np.array([AC_display, 0.0, 0.0])  # 沿 x 正方向
        B = np.array([0.0, CB_display, 0.0])   # 沿 y 正方向

        # 整体下移使图形居中
        offset_y = -0.8
        A = A + np.array([0, offset_y, 0])
        B = B + np.array([0, offset_y, 0])
        C = C + np.array([0, offset_y, 0])

        # 右下角文字位置（用于公式）
        formula_pos = np.array([3.5, 2.8, 0.0])
        result_pos = np.array([3.5, 1.8, 0.0])

        geometry = {
            'points': {
                'A': A,
                'B': B,
                'C': C,
            },
            'lines': {
                'AC': {'start': A, 'end': C, 'length': AC},
                'CB': {'start': C, 'end': B, 'length': CB},
                'AB': {'start': A, 'end': B, 'length': AB},
            },
            'circles': {},
            'angles': {
                'C': {'value': math.pi / 2, 'deg': 90.0},
            },
            'math': {
                'AC': AC,
                'CB': CB,
                'AB': AB,
                'AC_sq': AC ** 2,
                'CB_sq': CB ** 2,
                'AB_sq': AB ** 2,
                'sum_sq': AC ** 2 + CB ** 2,
            },
            'display': {
                'AC_display': AC_display,
                'CB_display': CB_display,
                'scale': scale,
            },
            'text_positions': {
                'formula_pos': formula_pos,
                'result_pos': result_pos,
            },
        }
        return geometry

    def assert_geometry(self, geometry):
        pts = geometry['points']
        A, B, C = pts['A'], pts['B'], pts['C']

        # 验证角 C 是直角 (向量 CA · CB = 0)
        CA = A - C
        CB_vec = B - C
        dot = np.dot(CA, CB_vec)
        assert abs(dot) < 1e-6, f"角C不是直角, dot={dot}"

        # 验证 AC = 3
        AC_len = np.linalg.norm(A - C)
        assert abs(AC_len - 3.0 * geometry['display']['scale']) < 1e-6, f"AC长度错误: {AC_len}"

        # 验证 CB = 4
        CB_len = np.linalg.norm(B - C)
        assert abs(CB_len - 4.0 * geometry['display']['scale']) < 1e-6, f"CB长度错误: {CB_len}"

        # 验证勾股定理: AB = 5
        AB_len = np.linalg.norm(A - B)
        expected_AB = 5.0 * geometry['display']['scale']
        assert abs(AB_len - expected_AB) < 1e-6, f"AB长度错误: {AB_len}, 期望 {expected_AB}"

        # 验证数学值
        assert abs(geometry['math']['AB'] - 5.0) < 1e-6, "AB数学值应等于5"

        self._check_canvas_bounds(geometry)
        print("[OK] Geometry validation passed")

    def define_elements(self, geometry):
        pts = geometry['points']
        elements = {}

        # 点
        elements['points'] = {}
        for name, coord in pts.items():
            dot = Dot(point=coord, color=self.COLORS['text'], radius=0.08)
            elements['points'][name] = dot

        # 顶点标签
        elements['labels'] = {}
        label_offsets = {
            'A': np.array([0.2, -0.3, 0]),
            'B': np.array([-0.3, 0.2, 0]),
            'C': np.array([-0.3, -0.3, 0]),
        }
        for name, coord in pts.items():
            label = Text(name, font_size=32, color=self.COLORS['text'])
            label.next_to(coord, direction=np.array([1, 0, 0]) if name == 'A' else (np.array([0, 1, 0]) if name == 'B' else np.array([0, 0, 0])), buff=0.15)
            # 手动调整位置
            if name == 'A':
                label.move_to(coord + np.array([0.35, -0.05, 0]))
            elif name == 'B':
                label.move_to(coord + np.array([-0.15, 0.35, 0]))
            else:
                label.move_to(coord + np.array([-0.15, -0.35, 0]))
            elements['labels'][name] = label

        # 边 - CA（蓝色，因为已知）
        elements['lines'] = {}
        line_cfg = geometry['lines']
        for name, cfg in line_cfg.items():
            line = Line(start=cfg['start'], end=cfg['end'], color=self.COLORS['primary'], stroke_width=4)
            elements['lines'][name] = line

        # 直角标记（在C点）
        right_angle_size = 0.3
        C = pts['C']
        A = pts['A']
        B = pts['B']
        # 从 C 指向 A 和 B 的单位方向
        dir_CA = (A - C) / np.linalg.norm(A - C)
        dir_CB = (B - C) / np.linalg.norm(B - C)
        # 直角标记的两条短边
        ra_p1 = C + dir_CA * right_angle_size
        ra_p2 = C + dir_CA * right_angle_size + dir_CB * right_angle_size
        ra_p3 = C + dir_CB * right_angle_size
        right_angle_mark = Polygon(
            ra_p1, ra_p2, ra_p3,
            color=self.COLORS['highlight'], stroke_width=2, fill_opacity=0
        )
        elements['right_angle_mark'] = right_angle_mark

        # 边长标注
        elements['side_labels'] = {}
        # AC 中点
        AC_mid = (pts['A'] + pts['C']) / 2
        AC_label = MathTex(r"3", font_size=36, color=self.COLORS['highlight'])
        AC_label.next_to(AC_mid, DOWN, buff=0.15)
        elements['side_labels']['AC'] = AC_label

        # CB 中点
        CB_mid = (pts['C'] + pts['B']) / 2
        CB_label = MathTex(r"4", font_size=36, color=self.COLORS['highlight'])
        CB_label.next_to(CB_mid, LEFT, buff=0.25)
        elements['side_labels']['CB'] = CB_label

        # AB 中点
        AB_mid = (pts['A'] + pts['B']) / 2
        # AB 标签放在斜边外侧
        AB_normal = np.array([-1, -1, 0]) / np.sqrt(2)
        AB_label = MathTex(r"AB", font_size=36, color=self.COLORS['secondary'])
        AB_label.next_to(AB_mid, RIGHT, buff=0.2)
        elements['side_labels']['AB'] = AB_label

        return elements

    def play_scene_1(self, elements, geometry):
        expected = self.start_scene_with_audio(1)

        title = Text("勾股定理应用", font_size=54, color=self.COLORS['highlight'])
        title.move_to(np.array([0, 2.0, 0]))
        self.play(Write(title), run_time=1.5)

        question = Text("求直角三角形ABC中AB的长度", font_size=30, color=self.COLORS['text'])
        question.move_to(np.array([0, 0.5, 0]))
        self.play(FadeIn(question), run_time=1.0)

        condition1 = MathTex(r"\angle C = 90^\circ, \quad AC = 3, \quad CB = 4",
                              font_size=36, color=self.COLORS['text'])
        condition1.move_to(np.array([0, -0.8, 0]))
        self.play(Write(condition1), run_time=1.5)

        self.subtitle = self.create_subtitle("")

        self.wait_until_scene_time(expected - 0.5)
        self.end_scene_with_audio(expected)

    def play_scene_2(self, elements, geometry):
        expected = self.start_scene_with_audio(2)

        # 清除标题区
        if hasattr(self, 'subtitle'):
            pass

        # 创建三角形组
        triangle_group = VGroup()
        triangle_group.add(elements['lines']['AC'])
        triangle_group.add(elements['lines']['CB'])
        triangle_group.add(elements['lines']['AB'])
        triangle_group.add(elements['points']['A'])
        triangle_group.add(elements['points']['B'])
        triangle_group.add(elements['points']['C'])

        self.play(Create(elements['lines']['AC']), run_time=1.0)
        self.play(Create(elements['lines']['CB']), run_time=1.0)
        self.play(Create(elements['lines']['AB']), run_time=1.0)
        self.play(
            FadeIn(elements['points']['A']),
            FadeIn(elements['points']['B']),
            FadeIn(elements['points']['C']),
            run_time=0.8
        )
        self.play(Write(elements['labels']['A']), run_time=0.5)
        self.play(Write(elements['labels']['B']), run_time=0.5)
        self.play(Write(elements['labels']['C']), run_time=0.5)

        self.wait_for_narration("互相垂直")
        # 高亮直角标记
        self.play(Create(elements['right_angle_mark']), run_time=0.8)

        self.end_scene_with_audio(expected)

    def play_scene_3(self, elements, geometry):
        expected = self.start_scene_with_audio(3)

        # 显示边长标签
        self.play(Write(elements['side_labels']['AC']), run_time=0.8)
        self.wait_for_narration("CB等于4")
        self.play(Write(elements['side_labels']['CB']), run_time=0.8)
        self.wait_for_narration("我们要求的那条边")
        self.play(Write(elements['side_labels']['AB']), run_time=0.8)

        # 高亮 AC
        self.highlight_element(elements['lines']['AC'], color=self.COLORS['secondary'], scale=1.0, duration=0.6)
        self.wait_for_narration("AC")

        # 高亮 CB
        self.highlight_element(elements['lines']['CB'], color=self.COLORS['highlight'], scale=1.0, duration=0.6)

        # 高亮 AB (目标)
        self.highlight_element(elements['lines']['AB'], color=self.COLORS['secondary'], scale=1.1, duration=0.8)

        self.end_scene_with_audio(expected)

    def play_scene_4(self, elements, geometry):
        expected = self.start_scene_with_audio(4)

        # 在屏幕右侧显示勾股定理公式
        formula_title = Text("勾股定理", font_size=36, color=self.COLORS['highlight'])
        formula_title.move_to(np.array([3.2, 3.0, 0]))

        formula = MathTex(r"AC^2 + CB^2 = AB^2", font_size=40, color=self.COLORS['text'])
        formula.move_to(np.array([3.2, 2.2, 0]))

        self.play(Write(formula_title), run_time=1.0)
        self.wait_for_narration("勾股定理")
        self.play(Write(formula), run_time=1.5)

        # 高亮 AC^2
        ac_box = SurroundingRectangle(formula[0][0:3], color=self.COLORS['secondary'], buff=0.05)
        self.play(Create(ac_box), run_time=0.6)
        self.wait_for_narration("AC的平方")

        # 高亮 CB^2
        cb_box = SurroundingRectangle(formula[0][3:6], color=self.COLORS['highlight'], buff=0.05)
        self.play(Create(cb_box), run_time=0.6)
        self.wait_for_narration("CB的平方")

        # 高亮 AB^2
        ab_box = SurroundingRectangle(formula[0][6:], color=self.COLORS['secondary'], buff=0.05)
        self.play(Create(ab_box), run_time=0.6)

        self.end_scene_with_audio(expected)

    def play_scene_5(self, elements, geometry):
        expected = self.start_scene_with_audio(5)

        # 显示代入数值步骤
        step1 = MathTex(r"AB^2 = 3^2 + 4^2", font_size=42, color=self.COLORS['text'])
        step1.move_to(np.array([3.2, 1.0, 0]))
        self.play(Write(step1), run_time=1.2)
        self.wait_for_narration("代入数值")

        step2 = MathTex(r"= 9 + 16", font_size=42, color=self.COLORS['text'])
        step2.move_to(np.array([3.2, 0.0, 0]))
        self.wait_for_narration("等于9")
        self.play(Write(step2), run_time=1.0)

        step3 = MathTex(r"= 25", font_size=42, color=self.COLORS['highlight'])
        step3.move_to(np.array([3.2, -1.0, 0]))
        self.wait_for_narration("25")
        self.play(Write(step3), run_time=0.8)

        step4 = MathTex(r"AB = \sqrt{25} = 5", font_size=44, color=self.COLORS['highlight'])
        step4.move_to(np.array([3.2, -2.0, 0]))
        self.wait_for_narration("根号25")
        self.play(Write(step4), run_time=1.2)

        # 高亮 AB 边
        self.highlight_element(elements['lines']['AB'], color=self.COLORS['highlight'], scale=1.15, duration=1.0)

        self.end_scene_with_audio(expected)

    def play_scene_6(self, elements, geometry):
        expected = self.start_scene_with_audio(6)

        # 显示最终结论
        conclusion_title = Text("结论", font_size=44, color=self.COLORS['highlight'])
        conclusion_title.move_to(np.array([0, 3.3, 0]))
        self.play(Write(conclusion_title), run_time=1.0)

        conclusion = MathTex(r"AB = 5", font_size=56, color=self.COLORS['highlight'])
        conclusion.move_to(np.array([0, 2.3, 0]))
        self.play(Write(conclusion), run_time=1.2)

        # 经典勾股数组说明
        classic = Text("3-4-5 经典勾股数组", font_size=32, color=self.COLORS['text'])
        classic.move_to(np.array([0, 1.2, 0]))
        self.wait_for_narration("经典")
        self.play(Write(classic), run_time=1.2)

        # 高亮整个三角形
        self.highlight_element(elements['lines']['AB'], color=self.COLORS['highlight'], scale=1.1, duration=0.8)
        self.highlight_element(elements['lines']['AC'], color=self.COLORS['secondary'], scale=1.05, duration=0.6)
        self.highlight_element(elements['lines']['CB'], color=self.COLORS['highlight'], scale=1.05, duration=0.6)

        # 闪烁最终答案
        self.wait_for_narration("AB等于5")
        self.play(
            conclusion.animate.scale(1.3).set_color(self.COLORS['secondary']),
            run_time=0.6
        )
        self.play(
            conclusion.animate.scale(1/1.3).set_color(self.COLORS['highlight']),
            run_time=0.6
        )

        self.end_scene_with_audio(expected)
