# Auto-generated by Claude Code Generation Mode
# Record ID: 43
# Generated at: 2026-07-05 15:18:01

from manim import *
import numpy as np
import math
import sys
import os

# 添加项目根目录到路径
sys.path.insert(0, r"C:\Users\lxy\WorkBuddy\2026-06-30-16-26-23\education_agent")

# 设置音频目录环境变量（使用绝对路径）
os.environ["MATHANIM_AUDIO_DIR"] = r"C:\Users\lxy\WorkBuddy\2026-06-30-16-26-23\education_agent\output\audio\run_20260705_151750"
os.environ["MATHANIM_VIDEO_OUTPUT"] = r"C:\Users\lxy\WorkBuddy\2026-06-30-16-26-23\education_agent\output\videos"

# 导入基类
from animation.base_scene import MathAnimScene

# 设置渲染参数
config.pixel_width = 1920
config.pixel_height = 1080
config.frame_rate = 60

from manim import *
import numpy as np


class MathProblemScene(MathAnimScene):
    """求圆的面积，半径为5"""

    SCENES = [
        (1, "开场", "audio_001_开场.mp3", None),
        (2, "画圆", "audio_002_画圆.mp3", None),
        (3, "标注半径", "audio_003_标注半径.mp3", None),
        (4, "推导公式", "audio_004_推导公式.mp3", None),
        (5, "代入计算", "audio_005_代入计算.mp3", None),
        (6, "总结", "audio_006_总结.mp3", None),
    ]

    def calculate_geometry(self):
        """计算所有几何坐标"""
        geometry = {}
        geometry['meta'] = {
            'radius': 5,
            'area': 25 * np.pi,
        }

        # 使用显示半径2.0来在屏幕上绘制圆
        display_radius = 2.0
        center = np.array([0.0, 0.0, 0.0])

        # 圆心
        geometry['center'] = center
        geometry['display_radius'] = display_radius

        # 圆上的几个关键点（用于标注半径）
        points = {}
        # 右侧点（用于画半径线）
        points['P_right'] = center + np.array([display_radius, 0.0, 0.0])
        # 顶部点
        points['P_top'] = center + np.array([0.0, display_radius, 0.0])
        # 左侧点
        points['P_left'] = center + np.array([-display_radius, 0.0, 0.0])
        # 底部点
        points['P_bottom'] = center + np.array([0.0, -display_radius, 0.0])

        # 用于扇形展示面积的小扇形上的点
        points['arc_start'] = points['P_right']
        points['arc_end'] = center + np.array(
            [display_radius * np.cos(np.pi / 6), display_radius * np.sin(np.pi / 6), 0.0]
        )

        geometry['points'] = points
        return geometry

    def assert_geometry(self, geometry):
        """验证几何正确性"""
        # 验证半径
        assert geometry['meta']['radius'] == 5, "半径应为5"
        # 验证面积
        expected_area = 25 * np.pi
        assert abs(geometry['meta']['area'] - expected_area) < 1e-6, "面积应为25π"
        # 验证显示半径在合理范围内
        assert 1.0 < geometry['display_radius'] < 3.0, "显示半径应在合理范围内"
        # 检查画布范围
        self._check_canvas_bounds(geometry)
        print("[OK] 几何验证通过")

    def define_elements(self, geometry):
        """创建Manim对象"""
        elements = {
            'points': {},
            'lines': {},
            'shapes': {},
            'labels': {},
            'formulas': {},
        }

        center = geometry['center']
        display_radius = geometry['display_radius']
        points = geometry['points']

        # 圆心
        elements['points']['O'] = Dot(center, color=self.COLORS['highlight'], radius=0.08)
        elements['labels']['O'] = Text("O", font_size=32, color=self.COLORS['highlight'])
        elements['labels']['O'].next_to(center, DOWN + LEFT, buff=0.15)

        # 圆
        circle = Circle(radius=display_radius, color=self.COLORS['primary'], stroke_width=4)
        circle.move_to(center)
        elements['shapes']['circle'] = circle

        # 半径线（从圆心到右侧点）
        radius_line = Line(center, points['P_right'], color=self.COLORS['secondary'], stroke_width=4)
        elements['lines']['radius'] = radius_line

        # 半径标签
        elements['labels']['r'] = Text("r", font_size=36, color=self.COLORS['secondary'])
        elements['labels']['r'].next_to(radius_line, UP, buff=0.15)

        # 半径数值标注
        elements['labels']['r_value'] = MathTex(r"r = 5", font_size=36, color=self.COLORS['highlight'])
        elements['labels']['r_value'].move_to(np.array([3.5, 1.5, 0.0]))

        # 面积公式
        elements['formulas']['area_formula'] = MathTex(
            r"S = \pi r^{2}",
            font_size=48,
            color=self.COLORS['highlight']
        )
        elements['formulas']['area_formula'].move_to(np.array([0.0, 3.2, 0.0]))

        # 代入步骤公式
        elements['formulas']['substitute'] = MathTex(
            r"S = \pi \times 5^{2}",
            font_size=42,
            color=self.COLORS['text']
        )
        elements['formulas']['substitute'].move_to(np.array([0.0, -3.0, 0.0]))

        # 最终结果
        elements['formulas']['result'] = MathTex(
            r"S = 25\pi",
            font_size=54,
            color=self.COLORS['highlight']
        )
        elements['formulas']['result'].move_to(np.array([0.0, -3.0, 0.0]))

        return elements

    def play_scene_1(self, elements, geometry):
        """第1幕：开场"""
        expected = self.start_scene_with_audio(1)

        # 标题
        title = Text("求圆的面积", font_size=60, color=self.COLORS['highlight'])
        title.move_to(np.array([0.0, 1.5, 0.0]))

        subtitle = Text("半径 r = 5", font_size=40, color=self.COLORS['text'])
        subtitle.move_to(np.array([0.0, 0.0, 0.0]))

        question_label = Text("求圆的面积 S = ?", font_size=36, color=self.COLORS['primary'])
        question_label.move_to(np.array([0.0, -1.5, 0.0]))

        self.play(Write(title), run_time=1.5)
        self.wait_for_narration("求圆的面积")
        self.play(FadeIn(subtitle, shift=UP), run_time=1.0)
        self.wait_for_narration("半径是5")
        self.play(FadeIn(question_label, shift=UP), run_time=1.0)
        self.wait_for_narration("计算这个圆的面积")

        self.play(FadeOut(title), FadeOut(subtitle), FadeOut(question_label), run_time=0.8)

        self.end_scene_with_audio(expected)

    def play_scene_2(self, elements, geometry):
        """第2幕：画圆"""
        expected = self.start_scene_with_audio(2)

        center = geometry['center']
        circle = elements['shapes']['circle']
        dot_O = elements['points']['O']
        label_O = elements['labels']['O']

        # 画圆心
        self.play(FadeIn(dot_O, scale=0.5), run_time=0.8)
        self.wait_for_narration("圆心为O")
        self.play(Write(label_O), run_time=0.6)

        # 画圆
        self.play(Create(circle), run_time=2.0)
        self.wait_for_narration("画一个圆心为O")
        self.wait_for_narration("半径为5的圆")

        # 标注r
        radius_line = elements['lines']['radius']
        label_r = elements['labels']['r']

        self.play(ShowPassingFlash(radius_line, time_width=0.5, run_time=1.5))
        self.wait_for_narration("用r来表示半径")
        self.play(Create(radius_line), Write(label_r), run_time=1.0)

        self.end_scene_with_audio(expected)

    def play_scene_3(self, elements, geometry):
        """第3幕：标注半径"""
        expected = self.start_scene_with_audio(3)

        radius_line = elements['lines']['radius']
        label_r = elements['labels']['r']
        r_value = elements['labels']['r_value']

        # 高亮半径线
        self.highlight_element(radius_line, color=self.COLORS['highlight'], scale=1.1)
        self.wait_for_narration("标注出半径")
        self.play(Indicate(label_r, color=self.COLORS['highlight'], scale_factor=1.5), run_time=1.0)
        self.wait_for_narration("r等于5")

        # 显示数值
        self.play(FadeIn(r_value, shift=RIGHT), run_time=1.0)
        self.wait_for_narration("圆上所有的点到圆心的距离都等于半径5")

        # 短暂等待
        self.wait(0.5)

        self.end_scene_with_audio(expected)

    def play_scene_4(self, elements, geometry):
        """第4幕：推导公式"""
        expected = self.start_scene_with_audio(4)

        # 隐藏之前的部分内容以腾出空间
        radius_line = elements['lines']['radius']
        label_r = elements['labels']['r']
        r_value = elements['labels']['r_value']
        circle = elements['shapes']['circle']
        dot_O = elements['points']['O']
        label_O = elements['labels']['O']

        # 把圆缩小并移到一侧，为公式腾出空间
        self.play(
            circle.animate.scale(0.6).move_to(np.array([-3.5, -0.5, 0.0])),
            dot_O.animate.move_to(np.array([-3.5, -0.5, 0.0])),
            label_O.animate.next_to(np.array([-3.5, -0.5, 0.0]), DOWN + LEFT, buff=0.1).scale(0.7),
            FadeOut(radius_line),
            FadeOut(label_r),
            FadeOut(r_value),
            run_time=1.5
        )

        # 显示面积公式
        area_formula = elements['formulas']['area_formula']
        self.play(Write(area_formula), run_time=2.0)
        self.wait_for_narration("圆的面积公式")
        self.wait_for_narration("S等于π乘以r的平方")

        # 高亮公式关键部分
        self.play(Indicate(area_formula, color=self.COLORS['highlight'], scale_factor=1.15), run_time=1.0)
        self.wait_for_narration("核心公式")
        self.wait_for_narration("牢记")

        self.end_scene_with_audio(expected)

    def play_scene_5(self, elements, geometry):
        """第5幕：代入计算"""
        expected = self.start_scene_with_audio(5)

        area_formula = elements['formulas']['area_formula']
        substitute = elements['formulas']['substitute']
        result = elements['formulas']['result']

        # 把公式上移
        self.play(area_formula.animate.move_to(np.array([0.0, 2.2, 0.0])), run_time=0.8)
        self.wait_for_narration("把r等于5代入公式")

        # 显示代入步骤
        self.play(FadeIn(substitute, shift=UP), run_time=1.5)
        self.wait_for_narration("S等于π乘以5的平方")

        # 转化为最终结果
        self.play(
            Transform(substitute, result, path_arc=-PI / 2),
            run_time=1.5
        )
        self.wait_for_narration("也就是25π")
        self.wait_for_narration("圆的面积是25π")

        # 高亮结果
        self.highlight_element(result, color=self.COLORS['highlight'], scale=1.2)

        self.end_scene_with_audio(expected)

    def play_scene_6(self, elements, geometry):
        """第6幕：总结"""
        expected = self.start_scene_with_audio(6)

        # 清除中间内容
        circle = elements['shapes']['circle']
        dot_O = elements['points']['O']
        label_O = elements['labels']['O']
        area_formula = elements['formulas']['area_formula']

        self.play(
            FadeOut(circle),
            FadeOut(dot_O),
            FadeOut(label_O),
            FadeOut(area_formula),
            run_time=1.0
        )

        # 展示总结
        summary_title = Text("最终答案", font_size=48, color=self.COLORS['text'])
        summary_title.move_to(np.array([0.0, 2.0, 0.0]))

        final_answer = MathTex(r"S = 25\pi", font_size=72, color=self.COLORS['highlight'])
        final_answer.move_to(np.array([0.0, 0.3, 0.0]))

        note_text = Text("当 r = 5 时", font_size=32, color=self.COLORS['text'])
        note_text.move_to(np.array([0.0, -1.5, 0.0]))

        self.play(Write(summary_title), run_time=1.0)
        self.wait_for_narration("总结一下")

        self.play(Write(final_answer), run_time=1.5)
        self.wait_for_narration("圆的面积S等于25π")
        self.wait_for_narration("最终答案")

        self.play(FadeIn(note_text, shift=UP), run_time=0.8)

        # 高亮最终答案
        self.highlight_element(final_answer, color=self.COLORS['secondary'], scale=1.15)

        self.end_scene_with_audio(expected)
