# Auto-generated by Claude Code Generation Mode
# Record ID: 38
# Generated at: 2026-07-05 01:39:27

from manim import *
import numpy as np
import sys
import os

# 添加项目根目录到路径
sys.path.insert(0, r"C:\Users\lxy\WorkBuddy\2026-06-30-16-26-23\education_agent")

# 设置音频目录环境变量（使用绝对路径）
os.environ["MATHANIM_AUDIO_DIR"] = r"C:\Users\lxy\WorkBuddy\2026-06-30-16-26-23\education_agent\output\audio\run_20260705_013916"
os.environ["MATHANIM_VIDEO_OUTPUT"] = r"C:\Users\lxy\WorkBuddy\2026-06-30-16-26-23\education_agent\output\videos"

# 导入基类
from animation.base_scene import MathAnimScene

# 设置渲染参数
config.pixel_width = 1920
config.pixel_height = 1080
config.frame_rate = 60

from manim import *
import numpy as np


class MathProblemScene(MathAnimScene):

    SCENES = [
        (1, "开场", "audio_001_开场.mp3", None),
        (2, "画圆", "audio_002_画圆.mp3", None),
        (3, "公式引入", "audio_003_公式引入.mp3", None),
        (4, "代入计算", "audio_004_代入计算.mp3", None),
        (5, "得出结果", "audio_005_得出结果.mp3", None),
        (6, "总结", "audio_006_总结.mp3", None),
    ]

    def calculate_geometry(self):
        radius = 5.0
        center = np.array([0.0, 0.0, 0.0])

        geometry = {
            'radius': radius,
            'center': center,
            'points': {
                'O': center,
                'P_right': center + np.array([radius, 0.0, 0.0]),
                'P_left': center + np.array([-radius, 0.0, 0.0]),
                'P_top': center + np.array([0.0, radius, 0.0]),
                'P_bottom': center + np.array([0.0, -radius, 0.0]),
            },
            'circle_center': center,
            'circle_radius': 1.5,
            'display_radius': radius,
            'area': 25 * np.pi,
            'area_approx': 78.5,
            'lines': {
                'r_right': {
                    'start': center,
                    'end': center + np.array([1.5, 0.0, 0.0]),
                },
                'r_diagonal': {
                    'start': center,
                    'end': center + np.array([1.5 * np.cos(np.pi / 4), 1.5 * np.sin(np.pi / 4), 0.0]),
                },
            },
            'labels': {
                'O': center + np.array([-0.3, -0.3, 0.0]),
                'r_label': center + np.array([0.8, 0.25, 0.0]),
                '5_label': center + np.array([1.7, -0.3, 0.0]),
                'formula_pos': np.array([0.0, 2.8, 0.0]),
                'sub_pos': np.array([0.0, 1.8, 0.0]),
                'result_pos': np.array([0.0, -2.8, 0.0]),
            },
            'angles': {},
        }
        return geometry

    def assert_geometry(self, geometry):
        assert geometry['radius'] == 5.0
        assert geometry['area'] == 25 * np.pi
        assert abs(geometry['area_approx'] - 78.5) < 0.1
        self._check_canvas_bounds(geometry)

    def define_elements(self, geometry):
        circle = Circle(
            radius=geometry['circle_radius'],
            color=self.COLORS['primary'],
            stroke_width=4,
        )
        circle.move_to(geometry['circle_center'])

        radius_line = Line(
            geometry['lines']['r_right']['start'],
            geometry['lines']['r_right']['end'],
            color=self.COLORS['secondary'],
            stroke_width=3,
        )

        radius_line2 = Line(
            geometry['lines']['r_diagonal']['start'],
            geometry['lines']['r_diagonal']['end'],
            color=self.COLORS['secondary'],
            stroke_width=3,
        )

        center_dot = Dot(
            geometry['points']['O'],
            radius=0.08,
            color=self.COLORS['highlight'],
        )

        label_O = Text(
            "O",
            font_size=32,
            color=self.COLORS['text'],
        )
        label_O.move_to(geometry['labels']['O'])

        label_r = MathTex(
            r"r",
            font_size=36,
            color=self.COLORS['highlight'],
        )
        label_r.move_to(geometry['labels']['r_label'])

        label_5 = Text(
            "5",
            font_size=36,
            color=self.COLORS['secondary'],
        )
        label_5.move_to(geometry['labels']['5_label'])

        formula = MathTex(
            r"S = \pi r^2",
            font_size=48,
            color=self.COLORS['highlight'],
        )
        formula.move_to(geometry['labels']['formula_pos'])

        sub_formula = MathTex(
            r"S = \pi \times 5^2",
            font_size=42,
            color=self.COLORS['text'],
        )
        sub_formula.move_to(geometry['labels']['sub_pos'])

        result = MathTex(
            r"S = 25\pi \approx 78.5",
            font_size=42,
            color=self.COLORS['primary'],
        )
        result.move_to(geometry['labels']['result_pos'])

        title = Text(
            "求圆的面积",
            font_size=54,
            color=self.COLORS['highlight'],
        )
        title.move_to(np.array([0.0, 2.0, 0.0]))

        subtitle = Text(
            "半径 r = 5",
            font_size=36,
            color=self.COLORS['text'],
        )
        subtitle.move_to(np.array([0.0, 0.8, 0.0]))

        elements = {
            'circle': circle,
            'radius_line': radius_line,
            'radius_line2': radius_line2,
            'center_dot': center_dot,
            'label_O': label_O,
            'label_r': label_r,
            'label_5': label_5,
            'formula': formula,
            'sub_formula': sub_formula,
            'result': result,
            'title': title,
            'subtitle': subtitle,
            'points': {
                'O': center_dot,
                'P_right': Dot(geometry['points']['P_right'], radius=0.05, color=self.COLORS['secondary']),
                'P_top': Dot(geometry['points']['P_top'], radius=0.05, color=self.COLORS['secondary']),
            },
            'lines': {
                'r_right': radius_line,
                'r_diagonal': radius_line2,
            },
            'labels': {
                'O': label_O,
                'r': label_r,
                '5': label_5,
                'formula': formula,
                'sub_formula': sub_formula,
                'result': result,
                'title': title,
                'subtitle': subtitle,
            },
        }
        return elements

    def play_scene_1(self, elements, geometry):
        expected = self.start_scene_with_audio(1)

        self.create_subtitle("求圆的面积，半径为5")
        self.fade_in(elements['title'])

        self.wait_for_narration("圆的面积")
        self.wait_for_narration("今天")

        self.fade_in(elements['subtitle'])

        self.wait_until_scene_time(expected * 0.7)

        self.end_scene_with_audio(expected)

    def play_scene_2(self, elements, geometry):
        expected = self.start_scene_with_audio(2)

        self.create_subtitle("画一个圆，标注圆心和半径")

        self.fade_in(elements['circle'])

        self.wait_for_narration("画一个圆")
        self.fade_in(elements['center_dot'])
        self.fade_in(elements['label_O'])

        self.wait_for_narration("标出圆心")
        self.fade_in(elements['radius_line'])
        self.fade_in(elements['label_r'])

        self.wait_for_narration("半径")
        self.fade_in(elements['label_5'])
        self.fade_in(elements['radius_line2'])

        self.wait_until_scene_time(expected * 0.85)

        self.end_scene_with_audio(expected)

    def play_scene_3(self, elements, geometry):
        expected = self.start_scene_with_audio(3)

        self.create_subtitle("圆的面积公式")

        self.wait_for_narration("面积公式")
        self.fade_in(elements['formula'])

        self.wait_for_narration("S等于")
        self.highlight_element(elements['formula'], color=self.COLORS['secondary'])

        self.wait_until_scene_time(expected * 0.8)

        self.end_scene_with_audio(expected)

    def play_scene_4(self, elements, geometry):
        expected = self.start_scene_with_audio(4)

        self.create_subtitle("代入半径 r = 5")

        self.wait_for_narration("代入")
        self.fade_in(elements['sub_formula'])

        self.wait_for_narration("r等于5")
        self.highlight_element(elements['label_5'], color=self.COLORS['highlight'], scale=1.5)

        self.wait_until_scene_time(expected * 0.85)

        self.end_scene_with_audio(expected)

    def play_scene_5(self, elements, geometry):
        expected = self.start_scene_with_audio(5)

        self.create_subtitle("计算结果")

        self.wait_for_narration("5的平方")
        step_formula = MathTex(
            r"5^2 = 25",
            font_size=38,
            color=self.COLORS['text'],
        )
        step_formula.move_to(np.array([0.0, 0.5, 0.0]))
        self.fade_in(step_formula)

        self.wait_for_narration("25π")
        self.fade_in(elements['result'])

        self.wait_for_narration("78.5")
        self.highlight_element(elements['result'], color=self.COLORS['highlight'], scale=1.2)

        self.wait_until_scene_time(expected * 0.9)

        self.fade_out(step_formula)

        self.end_scene_with_audio(expected)

    def play_scene_6(self, elements, geometry):
        expected = self.start_scene_with_audio(6)

        self.create_subtitle("总结：面积 = 25π")

        self.wait_for_narration("总结")
        self.highlight_element(elements['circle'], color=self.COLORS['highlight'])

        self.wait_for_narration("25π")
        self.highlight_element(elements['result'], color=self.COLORS['highlight'], scale=1.3)

        self.wait_for_narration("解题过程")
        self.highlight_element(elements['formula'], color=self.COLORS['highlight'])

        self.wait_until_scene_time(expected * 0.9)

        self.end_scene_with_audio(expected)
