# Auto-generated by Claude Code Generation Mode
# Record ID: 42
# Generated at: 2026-07-05 15:09:22

from manim import *
import numpy as np
import math
import sys
import os

# 添加项目根目录到路径
sys.path.insert(0, r"C:\Users\lxy\WorkBuddy\2026-06-30-16-26-23\education_agent")

# 设置音频目录环境变量（使用绝对路径）
os.environ["MATHANIM_AUDIO_DIR"] = r"C:\Users\lxy\WorkBuddy\2026-06-30-16-26-23\education_agent\output\audio\run_20260705_150911"
os.environ["MATHANIM_VIDEO_OUTPUT"] = r"C:\Users\lxy\WorkBuddy\2026-06-30-16-26-23\education_agent\output\videos"

# 导入基类
from animation.base_scene import MathAnimScene

# 设置渲染参数
config.pixel_width = 1920
config.pixel_height = 1080
config.frame_rate = 60

from manim import *
import numpy as np


class MathProblemScene(MathAnimScene):

    SCENES = [
        (1, "开场", "audio_001_开场.mp3", None),
        (2, "画圆", "audio_002_画圆.mp3", None),
        (3, "展示公式", "audio_003_展示公式.mp3", None),
        (4, "代入数值", "audio_004_代入数值.mp3", None),
        (5, "计算结果", "audio_005_计算结果.mp3", None),
        (6, "总结", "audio_006_总结.mp3", None),
    ]

    def calculate_geometry(self):
        geometry = {}

        # Mathematical values
        radius = 5
        area = np.pi * radius ** 2  # 25π
        area_approx = np.pi * radius ** 2  # ~78.54

        # Display values - radius 5 mapped to ~2.0 for screen
        display_radius = 2.0
        center = np.array([0.0, 0.0, 0.0])

        # Generate points on the circle (36 points for smooth circle)
        num_points = 72
        circle_points = []
        for i in range(num_points):
            angle = 2 * np.pi * i / num_points
            x = center[0] + display_radius * np.cos(angle)
            y = center[1] + display_radius * np.sin(angle)
            circle_points.append(np.array([x, y, 0.0]))

        # Key points on circle
        point_top = np.array([center[0], center[1] + display_radius, 0.0])
        point_right = np.array([center[0] + display_radius, center[1], 0.0])
        point_left = np.array([center[0] - display_radius, center[1], 0.0])
        point_bottom = np.array([center[0], center[1] - display_radius, 0.0])

        # Radius line endpoints (from center to right point)
        radius_end = np.array([center[0] + display_radius, center[1], 0.0])

        geometry['math_values'] = {
            'radius': radius,
            'area': area,
            'area_approx': area_approx
        }

        geometry['points'] = {
            'O': center,
            'P_top': point_top,
            'P_right': point_right,
            'P_left': point_left,
            'P_bottom': point_bottom,
            'radius_end': radius_end
        }

        geometry['lines'] = {
            'radius': {
                'start': center.tolist(),
                'end': radius_end.tolist()
            }
        }

        geometry['circles'] = {
            'main': {
                'center': center.tolist(),
                'display_radius': display_radius,
                'math_radius': radius,
                'points': [p.tolist() for p in circle_points]
            }
        }

        geometry['display'] = {
            'center': center,
            'display_radius': display_radius,
            'circle_points': circle_points
        }

        return geometry

    def assert_geometry(self, geometry):
        # Verify mathematical facts
        assert geometry['math_values']['radius'] == 5, "Radius should be 5"
        expected_area = 25 * np.pi
        actual_area = geometry['math_values']['area']
        assert abs(actual_area - expected_area) < 0.001, \
            f"Area should be 25π, got {actual_area}"

        # Verify display coordinates are within canvas bounds
        self._check_canvas_bounds(geometry)

        # Verify display radius is reasonable
        display_radius = geometry['display']['display_radius']
        assert display_radius <= 3.0, "Display radius too large for canvas"
        assert display_radius >= 0.5, "Display radius too small"

        # Verify center is near origin
        center = geometry['display']['center']
        assert abs(center[0]) < 1.0, "Center x should be near origin"
        assert abs(center[1]) < 1.0, "Center y should be near origin"

        print("[OK] Geometry assertions passed")

    def define_elements(self, geometry):
        elements = {}
        elements['points'] = {}
        elements['lines'] = {}
        elements['labels'] = {}
        elements['circles'] = {}
        elements['formulas'] = {}

        display_radius = geometry['display']['display_radius']
        center = geometry['display']['center']
        circle_points = geometry['display']['circle_points']

        # Main circle using Polygon for thick stroke
        circle_poly = Polygon(
            *circle_points,
            color=self.COLORS['primary'],
            stroke_width=4,
            fill_opacity=0
        )
        elements['circles']['main'] = circle_poly

        # Filled circle with low opacity for area visualization
        circle_filled = Polygon(
            *circle_points,
            color=self.COLORS['primary'],
            fill_color=self.COLORS['primary'],
            fill_opacity=0.2,
            stroke_width=0
        )
        elements['circles']['filled'] = circle_filled

        # Center point O
        dot_O = Dot(center, color=self.COLORS['highlight'], radius=0.08)
        elements['points']['O'] = dot_O

        # Radius endpoint
        radius_end = geometry['points']['radius_end']
        dot_end = Dot(radius_end, color=self.COLORS['secondary'], radius=0.06)
        elements['points']['radius_end'] = dot_end

        # Radius line
        radius_line = Line(center, radius_end, color=self.COLORS['secondary'], stroke_width=3)
        elements['lines']['radius'] = radius_line

        # Label O
        label_O = Text("O", font_size=32, color=self.COLORS['highlight'], weight=BOLD)
        label_O.next_to(center, DOWN + LEFT, buff=0.15)
        elements['labels']['O'] = label_O

        # Label r on radius line
        midpoint_r = (center + radius_end) / 2
        label_r = MathTex(r"r = 5", font_size=30, color=self.COLORS['secondary'])
        label_r.next_to(midpoint_r, UP, buff=0.15)
        elements['labels']['r'] = label_r

        # Title text (will be shown in scene 1)
        title = Text("求圆的面积", font_size=54, color=self.COLORS['highlight'], weight=BOLD)
        title.move_to([0, 3.2, 0])
        elements['labels']['title'] = title

        # Formula elements
        # S = πr²
        formula_general = MathTex(r"S = \pi r^{2}", font_size=48, color=self.COLORS['text'])
        formula_general.move_to([0, 1.0, 0])
        elements['formulas']['general'] = formula_general

        # S = π × 5²
        formula_substituted = MathTex(r"S = \pi \times 5^{2}", font_size=48, color=self.COLORS['text'])
        formula_substituted.move_to([0, 1.0, 0])
        elements['formulas']['substituted'] = formula_substituted

        # S = 25π
        formula_result = MathTex(r"S = 25\pi", font_size=56, color=self.COLORS['highlight'], weight=BOLD)
        formula_result.move_to([0, 1.0, 0])
        elements['formulas']['result'] = formula_result

        # S ≈ 78.54
        formula_approx = MathTex(r"S \approx 78.54", font_size=44, color=self.COLORS['text'])
        formula_approx.move_to([0, -0.5, 0])
        elements['formulas']['approx'] = formula_approx

        return elements

    def play_scene_1(self, elements, geometry):
        expected = self.start_scene_with_audio(1)

        # Show title
        title = elements['labels']['title']
        self.play(Write(title), run_time=1.5)

        self.wait_for_narration("求圆的面积")

        # Show subtitle for problem statement
        subtitle = self.create_subtitle("已知半径 r = 5，求圆的面积 S")
        self.play(FadeIn(subtitle), run_time=0.5)

        self.wait_until_scene_time(expected - 0.5)
        self.play(FadeOut(subtitle), run_time=0.3)
        self.play(FadeOut(title), run_time=0.5)

        self.end_scene_with_audio(expected)

    def play_scene_2(self, elements, geometry):
        expected = self.start_scene_with_audio(2)

        # Draw the circle
        circle = elements['circles']['main']
        self.play(Create(circle), run_time=2.0)

        self.wait_for_narration("圆心")

        # Add center point and label
        dot_O = elements['points']['O']
        label_O = elements['labels']['O']
        self.play(FadeIn(dot_O), Write(label_O), run_time=0.8)

        self.wait_for_narration("半径")

        # Add radius line and label
        radius_line = elements['lines']['radius']
        dot_end = elements['points']['radius_end']
        label_r = elements['labels']['r']
        self.play(
            Create(radius_line),
            FadeIn(dot_end),
            Write(label_r),
            run_time=1.2
        )

        # Highlight the radius
        self.highlight_element(radius_line, color=self.COLORS['highlight'], scale=1.2, duration=0.6)

        self.end_scene_with_audio(expected)

    def play_scene_3(self, elements, geometry):
        expected = self.start_scene_with_audio(3)

        # Move circle slightly down to make room for formula
        circle = elements['circles']['main']
        filled = elements['circles']['filled']
        dot_O = elements['points']['O']
        label_O = elements['labels']['O']
        radius_line = elements['lines']['radius']
        dot_end = elements['points']['radius_end']
        label_r = elements['labels']['r']

        self.play(
            circle.animate.shift(DOWN * 1.2),
            filled.animate.shift(DOWN * 1.2),
            dot_O.animate.shift(DOWN * 1.2),
            label_O.animate.shift(DOWN * 1.2),
            radius_line.animate.shift(DOWN * 1.2),
            dot_end.animate.shift(DOWN * 1.2),
            label_r.animate.shift(DOWN * 1.2),
            run_time=1.0
        )

        self.wait_for_narration("面积公式")

        # Show the general formula
        formula_general = elements['formulas']['general']
        self.play(Write(formula_general), run_time=1.5)

        self.wait_for_narration("π")

        # Highlight each part of formula
        self.play(
            formula_general[0][0].animate.set_color(self.COLORS['highlight']),  # S
            formula_general[0][2].animate.set_color(self.COLORS['highlight']),  # r
            run_time=0.8
        )

        # Show filled circle to illustrate area
        self.play(FadeIn(filled), run_time=0.6)

        self.end_scene_with_audio(expected)

    def play_scene_4(self, elements, geometry):
        expected = self.start_scene_with_audio(4)

        formula_general = elements['formulas']['general']
        formula_substituted = elements['formulas']['substituted']

        self.wait_for_narration("代入")

        # Transform formula
        self.play(
            Transform(formula_general, formula_substituted),
            run_time=1.5
        )

        self.wait_for_narration("五的平方")

        # Highlight the 5² part
        new_formula = elements['formulas']['general']  # now showing substituted
        self.play(
            new_formula.animate.set_color(self.COLORS['highlight']),
            run_time=0.6
        )

        self.wait_for_narration("二十五π")

        # Show intermediate calculation 5² = 25
        calc_text = MathTex(r"5^{2} = 25", font_size=40, color=self.COLORS['secondary'])
        calc_text.move_to([0, -1.8, 0])
        self.play(Write(calc_text), run_time=1.0)
        self.wait(0.3)
        self.play(FadeOut(calc_text), run_time=0.5)

        self.end_scene_with_audio(expected)

    def play_scene_5(self, elements, geometry):
        expected = self.start_scene_with_audio(5)

        formula_current = elements['formulas']['general']  # substituted formula
        formula_result = elements['formulas']['result']
        formula_approx = elements['formulas']['approx']

        self.wait_for_narration("最终结果")

        # Transform to final result
        self.play(
            Transform(formula_current, formula_result),
            run_time=1.5
        )

        self.wait_for_narration("近似值")

        # Show approximate value
        self.play(Write(formula_approx), run_time=1.0)

        self.wait_for_narration("七十八点五四")

        # Highlight the approximate value
        self.highlight_element(formula_approx, color=self.COLORS['highlight'], scale=1.15, duration=0.6)

        self.end_scene_with_audio(expected)

    def play_scene_6(self, elements, geometry):
        expected = self.start_scene_with_audio(6)

        formula_result = elements['formulas']['general']  # now showing result
        formula_approx = elements['formulas']['approx']
        circle = elements['circles']['main']
        filled = elements['circles']['filled']
        radius_line = elements['lines']['radius']

        self.wait_for_narration("总结")

        # Create summary box
        summary_title = Text("解题总结", font_size=40, color=self.COLORS['highlight'], weight=BOLD)
        summary_title.move_to([0, 3.0, 0])
        self.play(Write(summary_title), run_time=0.8)

        self.wait_for_narration("S等于πr的平方")

        # Highlight the result formula
        self.highlight_element(formula_result, color=self.COLORS['highlight'], scale=1.2, duration=0.8)

        self.wait_for_narration("二十五π")

        # Highlight the circle area
        self.play(filled.animate.set_fill(opacity=0.4), run_time=0.6)
        self.highlight_element(circle, color=self.COLORS['highlight'], scale=1.05, duration=0.6)

        # Show subtitle
        final_subtitle = self.create_subtitle("圆的面积 S = πr² = 25π ≈ 78.54")
        self.play(FadeIn(final_subtitle), run_time=0.5)

        self.wait_until_scene_time(expected - 0.5)

        # Fade everything out
        self.play(
            *[FadeOut(mob) for mob in self.mobjects],
            run_time=0.8
        )

        self.end_scene_with_audio(expected)
