# Auto-generated by Claude Code Generation Mode
# Record ID: 46
# Generated at: 2026-07-05 16:13:47

from manim import *
import numpy as np
import math
import sys
import os

# 添加项目根目录到路径
sys.path.insert(0, r"C:\Users\lxy\WorkBuddy\2026-06-30-16-26-23\education_agent")

# 设置音频目录环境变量（使用绝对路径）
os.environ["MATHANIM_AUDIO_DIR"] = r"C:\Users\lxy\WorkBuddy\2026-06-30-16-26-23\education_agent\output\audio\run_20260705_161338"
os.environ["MATHANIM_VIDEO_OUTPUT"] = r"C:\Users\lxy\WorkBuddy\2026-06-30-16-26-23\education_agent\output\videos"

# 导入基类
from animation.base_scene import MathAnimScene

# 设置渲染参数
config.pixel_width = 1920
config.pixel_height = 1080
config.frame_rate = 60

from manim import *
import numpy as np

class MathProblemScene(MathAnimScene):

    SCENES = [
        (1, "开场", "audio_001_开场.mp3", None),
        (2, "画圆", "audio_002_画圆.mp3", None),
        (3, "标注已知条件", "audio_003_标注.mp3", None),
        (4, "推导公式", "audio_004_公式.mp3", None),
        (5, "代入计算", "audio_005_计算.mp3", None),
        (6, "总结", "audio_006_总结.mp3", None),
    ]

    def calculate_geometry(self):
        geometry = {}

        radius = 7.0
        display_radius = 2.0
        center = np.array([0.0, 0.0, 0.0])

        left_point = center + np.array([-display_radius, 0.0, 0.0])
        right_point = center + np.array([display_radius, 0.0, 0.0])
        up_point = center + np.array([0.0, display_radius, 0.0])

        angle = np.pi / 6
        label_radius_point = center + display_radius * np.array([np.cos(angle), np.sin(angle), 0.0])

        geometry['points'] = {
            'O': center,
            'P_right': right_point,
            'P_left': left_point,
            'P_up': up_point,
            'label_r': label_radius_point,
        }

        geometry['lines'] = {
            'radius_h': {
                'start': center,
                'end': right_point,
                'length': display_radius,
            },
            'radius_v': {
                'start': center,
                'end': up_point,
                'length': display_radius,
            },
        }

        geometry['circles'] = {
            'main': {
                'center': center,
                'radius': display_radius,
            },
        }

        geometry['angles'] = {}

        geometry['math'] = {
            'radius': radius,
            'r_squared': radius * radius,
            'area': radius * radius * np.pi,
            'display_radius': display_radius,
        }

        return geometry

    def assert_geometry(self, geometry):
        assert geometry['math']['radius'] == 7.0
        assert geometry['math']['r_squared'] == 49.0
        assert abs(geometry['math']['area'] - 49.0 * np.pi) < 1e-6
        self._check_canvas_bounds(geometry)
        print("[OK] Geometry verified: radius=7, area=49*pi")

    def define_elements(self, geometry):
        pts = geometry['points']
        elements = {}

        elements['dots'] = {}
        for name, pos in pts.items():
            d = Dot(point=pos, color=self.COLORS['highlight'], radius=0.06)
            elements['dots'][name] = d

        elements['lines'] = {}
        for name, cfg in geometry['lines'].items():
            ln = Line(
                start=cfg['start'],
                end=cfg['end'],
                color=self.COLORS['secondary'],
                stroke_width=4,
            )
            elements['lines'][name] = ln

        elements['circles'] = {}
        for name, cfg in geometry['circles'].items():
            circ = Circle(
                radius=cfg['radius'],
                color=self.COLORS['primary'],
                stroke_width=4,
            )
            circ.move_to(cfg['center'])
            elements['circles'][name] = circ

        elements['labels'] = {}
        label_O = Text("O", font_size=32, color=self.COLORS['highlight'])
        label_O.next_to(pts['O'], DOWN + LEFT, buff=0.15)
        elements['labels']['O'] = label_O

        label_r = MathTex(r"r = 7", font_size=36, color=self.COLORS['secondary'])
        label_r.next_to(
            (pts['O'] + pts['label_r']) / 2,
            UP + RIGHT,
            buff=0.15,
        )
        elements['labels']['r7'] = label_r

        formula = MathTex(r"S = \pi r^2", font_size=54, color=self.COLORS['text'])
        formula.move_to(np.array([0.0, 3.2, 0.0]))
        elements['labels']['formula'] = formula

        step1 = MathTex(r"S = \pi \\times 7^2", font_size=48, color=self.COLORS['text'])
        step1.move_to(np.array([0.0, 3.2, 0.0]))
        elements['labels']['step1'] = step1

        step2 = MathTex(r"S = 49\pi", font_size=54, color=self.COLORS['highlight'])
        step2.move_to(np.array([0.0, 3.2, 0.0]))
        elements['labels']['step2'] = step2

        title = Text("求圆的面积", font_size=48, color=self.COLORS['highlight'])
        title.move_to(np.array([0.0, 3.5, 0.0]))
        elements['labels']['title'] = title

        problem = MathTex(r"r = 7, \quad S = ?", font_size=40, color=self.COLORS['text'])
        problem.move_to(np.array([0.0, 2.5, 0.0]))
        elements['labels']['problem'] = problem

        conclusion = Text("半径为7的圆的面积", font_size=36, color=self.COLORS['text'])
        conclusion.move_to(np.array([0.0, 2.7, 0.0]))
        elements['labels']['conclusion'] = conclusion

        return elements

    def play_scene_1(self, elements, geometry):
        expected = self.start_scene_with_audio(1)

        title = elements['labels']['title']
        problem = elements['labels']['problem']

        self.play(Write(title), run_time=1.5)
        self.wait_for_narration("今天")
        self.play(FadeIn(problem, shift=UP), run_time=1.2)
        self.wait_for_narration("半径是7")
        self.wait(0.5)

        self.end_scene_with_audio(expected)

    def play_scene_2(self, elements, geometry):
        expected = self.start_scene_with_audio(2)

        title = elements['labels']['title']
        problem = elements['labels']['problem']

        self.play(FadeOut(title), FadeOut(problem), run_time=0.8)

        circ = elements['circles']['main']
        self.play(Create(circ), run_time=2.0)
        self.wait_for_narration("画一个圆")

        dot_O = elements['dots']['O']
        label_O = elements['labels']['O']
        self.play(FadeIn(dot_O, scale=0.5), Write(label_O), run_time=1.0)
        self.wait_for_narration("圆心标记为O")
        self.wait(0.3)

        self.end_scene_with_audio(expected)

    def play_scene_3(self, elements, geometry):
        expected = self.start_scene_with_audio(3)

        line_h = elements['lines']['radius_h']
        label_r = elements['labels']['r7']

        self.wait_for_narration("标注")
        self.play(Create(line_h), run_time=1.2)
        self.wait_for_narration("半径")
        self.play(Write(label_r), run_time=1.0)
        self.wait_for_narration("等于7")
        self.wait(0.5)

        self.end_scene_with_audio(expected)

    def play_scene_4(self, elements, geometry):
        expected = self.start_scene_with_audio(4)

        line_h = elements['lines']['radius_h']
        label_r = elements['labels']['r7']

        self.play(
            FadeOut(line_h),
            FadeOut(label_r),
            run_time=0.8,
        )

        formula = elements['labels']['formula']
        self.play(Write(formula), run_time=1.8)
        self.wait_for_narration("圆的面积公式")
        self.wait_for_narration("派乘以r的平方")
        self.wait(0.5)

        self.end_scene_with_audio(expected)

    def play_scene_5(self, elements, geometry):
        expected = self.start_scene_with_audio(5)

        formula = elements['labels']['formula']
        step1 = elements['labels']['step1']
        step2 = elements['labels']['step2']

        self.play(Transform(formula, step1), run_time=1.2)
        self.wait_for_narration("r等于7")
        self.wait_for_narration("49派")
        self.play(Transform(formula, step2), run_time=1.2)
        self.wait(0.3)

        self.end_scene_with_audio(expected)

    def play_scene_6(self, elements, geometry):
        expected = self.start_scene_with_audio(6)

        conclusion = elements['labels']['conclusion']
        formula = elements['labels']['step2']
        circ = elements['circles']['main']
        dot_O = elements['dots']['O']
        label_O = elements['labels']['O']

        self.play(
            FadeOut(conclusion, shift=UP),
            run_time=0.8,
        )

        self.highlight_element(formula, color=self.COLORS['highlight'], scale=1.3, duration=1.5)
        self.wait_for_narration("半径为7")
        self.wait_for_narration("49派")

        self.play(
            circ.animate.set_stroke(width=6),
            dot_O.animate.set_color(self.COLORS['highlight']),
            label_O.animate.set_color(self.COLORS['highlight']),
            run_time=1.0,
        )
        self.wait(0.8)

        self.end_scene_with_audio(expected)
